modules/swagger-models/src/main/java/com/wordnik/swagger/models/ModelImpl.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/ObjectProperty.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/StringProperty.java
- string property with format uri and byte
- object property
- inheritance (see swagger.json)
- additional arguments (model/api package)
- some NPE eliminated
is needed for the improments in my pull requests for swagger-codegen
https://github.com/swagger-api/swagger-codegen/pull/349
=> Additional features in swagger-codegen, see https://github.com/swagger-api/swagger-codegen/pull/349

modules/swagger-core/src/test/scala/models/composition/Human.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Info.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Operation.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Path.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/parameters/AbstractParameter.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/parameters/Parameter.java
...to make them available to the code generator
Some are still missing:
* https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#pathsObject
* https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responsesObject
* https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#tagObject
* https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#securitySchemeObject
=> [spec_2.0] Vendor extensions implemented

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/scala/GuavaTest.scala
This was my first time digging through the project, so I'm not sure if I implemented this in the desired fashion.  The test now passes at the very least.
=> Add support for Guava Optional to core, fixes 609

modules/swagger-play2/app/play/modules/swagger/PlayApiScanner.scala
This log text fits info level.
re-resubmit of #907
=> [rere] fix incorrect log level

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jersey2-jaxrs/src/test/scala/ScannerTest.scala, modules/swagger-jersey2-jaxrs/src/test/scala/resources/ClassWithString.java, modules/swagger-jersey2-jaxrs/src/test/scala/resources/ResourceWithComplexBodyInputType.java
to generated swagger definition - see #906
hope this was the right approach - let me know otherwise :-)
=> fixed adding of definitions for complex body input parameters 

modules/swagger-core/src/test/scala/specFiles/compositionTest.json, samples/java-grails2/web-app/WEB-INF/applicationContext.xml, samples/java-jaxrs-cxf/src/main/resources/applicationContext.xml, samples/java-jaxrs-cxf/src/test/scala/ResourceListingIT.scala, samples/java-jaxrs-no-webxml/src/main/java/com/wordnik/swagger/sample/Bootstrap.java, samples/java-jaxrs-no-webxml/src/test/scala/ResourceListingIT.scala, samples/java-jaxrs/src/main/java/com/wordnik/swagger/sample/Bootstrap.java, samples/java-jaxrs/src/test/scala/ResourceListingIT.scala, samples/java-jersey-jaxrs/src/main/java/com/wordnik/swagger/sample/Bootstrap.java, samples/java-jersey2/src/main/java/com/wordnik/swagger/sample/Bootstrap.java
Hi! just changing the email addresses from apiteam@wordnik.com to apiteam@swagger.io
=> changing apiteam@wordnik.com to apiteam@swagger.io in 10 files

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/BeanConfig.java
fixes #983 
this should fix my reported issue (and is my first ever pull request on github, yeah :))
=> use better pattern to compare to empty resourcePackages

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/listing/SwaggerSerializers.java
=> Change SwaggerSerializers to use Yaml

modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/SubResourceScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/SubResourceHead.java, modules/swagger-jaxrs/src/test/scala/resources/SubResourceTail.java
Support of class-based sub-resources has been added.
=> Fixes #394. Support of class-based sub-resources has been added.

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/AbstractModelConverter.java
Removed redundant changes discussed here: https://github.com/swagger-api/swagger-core/pull/975#discussion-diff-28632625L38
=> Fixed #847. Removed redundant changes.

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/SubResourceScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/NoPathSubResource.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithSubResources.java, modules/swagger-jaxrs/src/test/scala/resources/SubResourceHead.java
Fixes #942: Path validation has been fixed.
=> Fixes #942: Path validation has been fixed.

modules/swagger-models/pom.xml, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Response.java
Fixes #988: Example field has been declared as object.
=> Fixes #988: Example field has been declared as object.

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/SimpleResource.java
There was missed setting of required Body Parameter in ParameterProcessor.
=> Issue #971. Fixed setting of body parameter if required.

modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/SwaggerJersey2Jaxrs.java, modules/swagger-jersey2-jaxrs/src/test/scala/SwaggerJersey2JaxrsTest.scala
=> Fixed #1015: @FormDataParam support in jersey2

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/ResourceWithScheme.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithScheme.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithoutScheme.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Operation.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Scheme.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/Swagger.java
Fixed #953: protocols() value in @Api and @ApiOperation should change and be parsed
=> Fixed #953: protocols() value in @Api and @ApiOperation should change and be parsed

modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/Api.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiImplicitParam.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiModel.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiModelProperty.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiOperation.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiParam.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiResponse.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiResponses.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/Authorization.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/AuthorizationScope.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ExternalDocs.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ResponseHeader.java
Modified them to better document the current usage in the 1.5 version.
=> Annotations javadoc updates

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/DefaultJaxrsConfig.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/DefaultReaderConfig.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/ReaderConfig.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/ReaderConfigUtils.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/listing/ApiListingResource.java, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithApiOperationCode.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithApiResponseResponseContainer.java, modules/swagger-jaxrs/src/test/scala/resources/SubResourceHead.java, modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/config/JerseyJaxrsConfig.java
Fixed #978: no-annotations support has been added.
=> Fixed #978: no-annotations support has been added.

modules/swagger-core/src/main/java/com/wordnik/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/scala/filter/SpecFilterTest.scala, modules/swagger-core/src/test/scala/specFiles/noModels.json
Fixed #1077: NPE has been fixed.
=> Fixed #1077: NPE has been fixed.

modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/models/Namespace.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithInnerClass.java
#976: Unit test for inner classes has been added.
=> #976: Unit test for inner classes has been added.

modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/models/EnumHolder.java, modules/swagger-jaxrs/src/test/scala/models/TestEnum.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithEnums.java, modules/swagger-jersey2-jaxrs/src/test/scala/SwaggerJersey2JaxrsTest.scala, modules/swagger-jersey2-jaxrs/src/test/scala/models/TestEnum.java, modules/swagger-jersey2-jaxrs/src/test/scala/params/EnumBean.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/parameters/AbstractSerializableParameter.java
Fixes #1019: Listing of enum values has been fixed.
=> Fixes #1019: Listing of enum values has been fixed.

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java
more specific securities
Sample output at https://gist.github.com/Amyntas/4ef69c7e4cf94852d5d2 check lines 197 and 198
=> #1041, Only add global @Api securities if operation doesn't already have

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java, modules/swagger-jaxrs/src/test/scala/PostParamTest.scala, modules/swagger-jaxrs/src/test/scala/models/Pet.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/AbstractProperty.java, modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/Property.java
Fixed #1027. ApiModelProperty#access support has been added
=> Fixed #1027. ApiModelProperty#access support has been added

modules/swagger-core/src/main/java/com/wordnik/swagger/converter/ModelConverters.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/ApiListingResourceTest.scala, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithBodyParams.java
Fixes #943: Handling of method parameters without @ApiParam annotations has been added.
=> Fixes #943: Handling of method parameters without @ApiParam has been added.

modules/swagger-core/src/test/scala/CompositionTest.scala, modules/swagger-core/src/test/scala/models/composition/AbstractBaseModelWithSubTypes.java, modules/swagger-core/src/test/scala/models/composition/ModelWithFieldWithSubTypes.java, modules/swagger-core/src/test/scala/models/composition/Thing1.java, modules/swagger-core/src/test/scala/models/composition/Thing2.java
The problem has been eliminated in fix for #847. Here is only a test in order to confirm this.
=> Fixed #852. Added a test for model with field with subtypes.

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/TypeNameResolver.java, modules/swagger-jaxrs/src/test/scala/GenericsTest.scala, modules/swagger-jaxrs/src/test/scala/models/GenericType.java, modules/swagger-jaxrs/src/test/scala/models/GenericTypeWithApiModel.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithGenerics.java
Fixed #1061: Composing of names for generic types has been improved.
=> Fixed #1061: Composing of names for generic types has been improved.

modules/swagger-core/src/main/java/com/wordnik/swagger/converter/ModelConverters.java, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/GenericsTest.scala, modules/swagger-jaxrs/src/test/scala/models/GenericListWrapper.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithGenerics.java
Fixed #498: Handling of generic responses has been fixed.
=> Fixed #498: Handling of generic responses has been fixed.

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/utils/ReflectionUtils.java, modules/swagger-jaxrs/src/test/scala/ReaderTest.scala, modules/swagger-jaxrs/src/test/scala/resources/AbstractResource.java, modules/swagger-jaxrs/src/test/scala/resources/DescendantResource.java, modules/swagger-jaxrs/src/test/scala/resources/InterfaceResource.java
Fixed #1091: Annotation detecting on overridden method has been fixed
=> Fixed #1091: Annotation detecting on overridden method has been fixed

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/AbstractModelConverter.java, modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/TypeNameResolver.java, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-core/src/test/scala/models/ModelWithFormattedStrings.java, modules/swagger-jaxrs/src/test/scala/GenericsTest.scala, modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/StringProperty.java
fixed #1121: Format for uuid, uri and url string proreties has been added
=> fixed #1121: Format for uuid, uri and url string proreties has been added

modules/swagger-core/pom.xml
=> updated guava version

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/ReaderTest.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithDeprecatedMethod.java
Fixes #1183: Processing of Deprecated annotation has been fixed
=> Fixes #1183: Processing of Deprecated annotation has been fixed

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java
Fixes #1185: unused code has been deleted.
=> Fixes #1185: unused code has been deleted.

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java
Fixed order of initialisation so annotations and custom processes don't get overridden
=> fixed initialization order

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java, modules/swagger-jaxrs/src/test/scala/ReaderTest.scala, modules/swagger-jaxrs/src/test/scala/resources/DescendantResource.java, modules/swagger-jaxrs/src/test/scala/resources/InterfaceResource.java
Fixes #1253: ArrayIndexOutOfBoundsException has been fixed
=> Fixes #1253: ArrayIndexOutOfBoundsException has been fixed

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java
ReflectionUtils has been refactored
=> ReflectionUtils has been refactored

modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java
Fixes #1175: logging level has been changed to DEBUG
=> Fixes #1175: logging level has been changed to DEBUG

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-core/src/test/scala/models/Model1155.java
Fixed #1155: Names inspection has been fixed.
=> Fixed #1155: Names inspection has been fixed.

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReaderUtils.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java, modules/swagger-jaxrs/src/test/scala/ReaderTest.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithKnownInjections.java, modules/swagger-jersey2-jaxrs/src/test/scala/SwaggerJersey2JaxrsTest.scala, modules/swagger-jersey2-jaxrs/src/test/scala/resources/ResourceWithKnownInjections.java
Added support Jersey2 annotations
=> Fixed #1191: Parameter annotations from the Jersey2 should be supported in constructor(field)-level injections

modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/scala/filter/SpecFilterTest.scala
Fixes #977: Tags have been filtered
=> Fixes #977: Tags have been filtered

modules/swagger-models/pom.xml
Cherry-picking change from master branch
=> #1285 - Added missing package export

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/PathUtils.java, modules/swagger-jaxrs/src/test/scala/PathUtilsTest.scala
Fixes #1153:parsing pathparams with regex has been fixed
=> Fixes #1153:parsing pathparams with regex has been fixed

modules/swagger-models/src/main/java/io/swagger/models/Path.java
=> Add HTTP "head" method support in Path model

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java
=> Fixes #1286 : Removed static modifier from initialized field in ApiListingResource

modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/DefaultJaxrsScanner.java, modules/swagger-jaxrs/src/test/java/io/swagger/DefaultJaxrsScannerTest.java, pom.xml
Fixes #1177: DefaultJaxrsScanner has been fixed
=> Fixes #1177: DefaultJaxrsScanner has been fixed

modules/swagger-core/src/test/java/io/swagger/parameter/ParameterSerializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java
Fixes #1368: DefaultValue has been fixed
=> Fixes #1368: DefaultValue has been fixed

modules/swagger-core/pom.xml
fix the issue of wrongly including io.swagger.models in swagger-core.jar.
=>  #1361 fix the pacakging issue caused by PR #1362

modules/swagger-core/src/test/java/io/swagger/model/override/OverrideTest.java
Reverts swagger-api/swagger-core#1407
=> Revert "'expected' and 'actual' wrong way around"

modules/swagger-core/src/test/java/io/swagger/ByteConverterTest.java, modules/swagger-core/src/test/java/io/swagger/CovariantGetterTest.java, modules/swagger-core/src/test/java/io/swagger/EnumPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/HiddenFieldTest.java, modules/swagger-core/src/test/java/io/swagger/JodaDateTimeConverterTest.java, modules/swagger-core/src/test/java/io/swagger/JodaLocalDateConverterTest.java, modules/swagger-core/src/test/java/io/swagger/ModelConverterTest.java, modules/swagger-core/src/test/java/io/swagger/ModelPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/RequiredFieldModelTest.java, modules/swagger-core/src/test/java/io/swagger/XMLGregorianCalendarTest.java, modules/swagger-core/src/test/java/io/swagger/model/override/CustomConverterTest.java, modules/swagger-core/src/test/java/io/swagger/model/override/SnakeCaseConverterTest.java, modules/swagger-core/src/test/java/io/swagger/models/ApiFirstRequiredFieldModel.java, modules/swagger-core/src/test/java/io/swagger/models/Children.java, modules/swagger-core/src/test/java/io/swagger/models/JCovariantGetter.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithEnumField.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithEnumProperty.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithModelPropertyOverrides.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithPrimitiveArray.java, modules/swagger-core/src/test/java/io/swagger/models/TestEnum.java, modules/swagger-core/src/test/java/io/swagger/models/XmlFirstRequiredFieldModel.java
Fixes #1206: Test from 1_3 folder have been migrated
=> Fixes #1206: Test from 1_3 folder have been migrated

modules/swagger-core/pom.xml, modules/swagger-core/src/test/java/io/swagger/ObjectPropertyTest.java, modules/swagger-hibernate-validations/pom.xml, modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/test/java/io/swagger/PostParamTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ResourceTest1343.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/Resource1343.java, modules/swagger-jersey-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/pom.xml, modules/swagger-models/pom.xml, modules/swagger-mule/pom.xml, pom.xml
Fixes #1203: scala and junit dependencies have been deleted
=> Fixes #1203: scala and junit dependencies have been deleted

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReaderUtils.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/BaseResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/BookResource.java
Fixes #1317: Processing parameters from base class has been fixed
=> Fixes #1317: Processing parameters from base class has been fixed

modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java
to fix the NullPointerException found by swagger-codegen's CI:
https://travis-ci.org/swagger-api/swagger-codegen/builds/81263483#L3799
P.S. it seems to be introduced in PR #1431
=> Add null-checking to addRequired

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
Fixes #1479: java.util.Optional processing has been added
=> Fixes #1479: java.util.Optional processing has been added

modules/swagger-jaxrs/src/test/java/io/swagger/SimpleScannerTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/NicknamedOperation.java
I started to fix a problem that apparently was already fixed in PR #1453 for issue #1440.  Looks like there wasn't a testcase added for the fix, so will offer that contribution.
=> Testcase for issue #1440 and PR #1453

modules/swagger-hibernate-validations/src/main/java/io/swagger/validator/BeanValidator.java, modules/swagger-hibernate-validations/src/test/java/io/swagger/HibernateBeanValidationsTest.java, modules/swagger-hibernate-validations/src/test/java/io/swagger/models/HibernateBeanValidationsModel.java
Hi just added support for hibernates @NotEmpty annotation which can be used on collections and strings (in contrast to @NotBlank which is only for strings)
=> Add support for @NotEmpty annotation

modules/swagger-core/src/test/java/io/swagger/ModelSerializerTest.java, modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java
=> add additional properties

modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/resources/specFiles/petstore.json, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/ScannerTest.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/resources/ResourceWithExtensions.java, modules/swagger-models/src/main/java/io/swagger/models/Operation.java, modules/swagger-models/src/main/java/io/swagger/models/Swagger.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/Reader.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ReaderExtension.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ServletReaderExtension.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/ReaderTest.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/extensions/ReaderExtension1.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/extensions/ReaderExtension2.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/resources/ResourceWithAnnotations.java
Also fixed the Servlet Reader to process extensions correctly.
=> Issue 1523 - @ApiOperation extensions not cloned in SpecFilter

modules/swagger-models/src/main/java/io/swagger/models/properties/ByteProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PasswordProperty.java
Following https://github.com/swagger-api/swagger-spec/issues/518
Added classes __ByteProperty__ and __PasswordProperty__.
=> Add classes ByteProperty and PasswordProperty

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleScannerTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/SimpleSelfReferencingSubResource.java
this should fix the issue correctly.
=> fix #1574 allow visit the same sub resources along different paths

modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java, modules/swagger-core/src/test/java/io/swagger/ByteConverterTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/BinaryProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ByteArrayProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/main/java/io/swagger/models/properties/StringProperty.java, modules/swagger-models/src/test/java/io/swagger/StringPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/models/properties/PropertyBuilderTest.java
=> fix for #1578, swapped byte and binary properties

modules/swagger-models/src/main/java/io/swagger/models/Operation.java
Add io.swagger.models.Operation.toString() for ease of use in a debugger.
=> Add io.swagger.models.Operation.toString().

modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java
=> added empty string check

modules/swagger-models/src/main/java/io/swagger/models/RefResponse.java, modules/swagger-models/src/test/java/io/swagger/models/RefResponseTest.java
=> Expose simple ref in RefResponse like in all the other RefTypes

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java
Fix for Bugs #1106 and #1614 
The parent-child looping logic is a bit weird.  Either way, we shouldn't be generating a new `Tag` for subResources; it should be using the parent tags.  If `@Api` was encountered on a subResource, it will get picked up as it's own root `Tag` and be handled separately from the parent (with a different path).
A second change was made on how to identify a subResource in the `getSubResource` method.  It shouldn't be required to have config that is `isScanAllResources() == true`.  "scan all resources" still applies for root Tags that are not annotated with `@Api`.
=> Fix Bugs 1106 and 1614

modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/AcceptHeaderApiListingResource.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/BaseApiListingResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/ApiListingResourceIT.java, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/model/Widget.java, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/resources/WidgetResource.java, modules/swagger-jaxrs/src/test/webapp/WEB-INF/web.xml, pom.xml
PR for #1620 
fixes #1620, fixes #1647
=> Refactor ApiListingResource to not use greedy @Path("/") annotation

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerContextService.java, modules/swagger-jaxrs/src/test/java/io/swagger/ApiListingResourceTest.java
Refs #1689, added Null check on ServletConfig.
=> Close #1689 - Null check on ServletConfig in ApiListingResource

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerContextService.java, modules/swagger-jaxrs/src/test/java/io/swagger/ApiListingResourceTest.java
Fix #1691. fixes ServletConfig related error in RESTEasy Filter based config (and other similar environments), adding tighter check.
=> Fix #1691 - fixes ServletConfig related error in RESTEasy Filter based config

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ApiConsumesProducesResource.java
Fix #1546. Fix #1609. It overlaps and replaces https://github.com/swagger-api/swagger-core/pull/1652
=> Fix #1546 - consumes and produces reading

modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/paramAndResponseRef.json
Fix #1707 - fixes NPE in case of model with no props or props filtered out by filter
=> Fix #1707 - Fix NPE in case of model with no props

modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/paramAndResponseRef.json
fixes https://github.com/swagger-api/swagger-core/issues/1707#issuecomment-195352317
=> Fix #1707 - correctly remove unused nested definitions

modules/swagger-core/src/test/java/io/swagger/ByteConverterTest.java
Changes:
- replace hard coded unix style line endings with a system dynamic implementation
- tested in a Windows 7 and Linux Centos 7 version (test successful on both OS versions)
=> Issue #1752: - fix line ending issue on windows

modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/DefaultParameterExtension.java, modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/SwaggerJersey2JaxrsTest.java, pom.xml
Fix #1648 
includes https://github.com/elakito/swagger-core/commit/2b88e4a891fadbe2df124d2d2e12d060aeadd938 and adds additional check for issue in #1648
=> Fix Issue #1648

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiKeyAuthDefinition.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/BasicAuthDefinition.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/OAuth2Definition.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/Scope.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/SecurityDefinition.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/SwaggerDefinition.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/Reader.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/resources/ResourceWithAnnotations.java
Fix Issue #1830 
Add security definition support to the SwaggerDefinition annotation
=> Add SecurityDefintion annotation, as well as child annotations

modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/paramAndResponseRefArray.json, modules/swagger-core/src/test/resources/specFiles/paramAndResponseRefComposed.json
Refs #1757 and updates PR #1758 adding ComposedModel support
=> Ref #1757- Retain refs from Array/Map Property types and ComposedModel when using "removingUnreferencedDefinitions"

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/SwaggerJersey2JaxrsTest.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/models/JacksonBean.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/resources/ResourceWithJacksonBean.java, modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/Property.java
Issue: https://github.com/swagger-api/swagger-core/issues/1682
=> Jackson JsonUnwrapped support

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/util/JsonDeserializationTest.java, modules/swagger-core/src/test/resources/json-schema-validation/array.json, modules/swagger-core/src/test/resources/json-schema-validation/map.json, modules/swagger-models/src/main/java/io/swagger/models/properties/MapProperty.java
parses minItems, maxItems and uniqueItems for array property.
parses minProperties and maxProperties for map property.
=> schema validation parsing for array and map

modules/swagger-jaxrs/src/test/java/io/swagger/models/Pet.java
Looks like this was just a typo
=> Fix setter so value is actually set

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ApiMultipleConsumesProducesResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/RsMultipleConsumesProducesResource.java, modules/swagger-jaxrs/src/test/resources/ResourceWithJsonIdentity.json
=> The order of consumes and produces is not conserved nor predictable if they are inherited from the parent.

modules/swagger-models/src/main/java/io/swagger/models/Path.java, modules/swagger-models/src/main/java/io/swagger/models/Swagger.java
=> Preserve order

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/ReaderTest.java
this PR has been created in order to fix to #1939
=> Fixed duplicate operation id when using inheritance

modules/swagger-models/src/main/java/io/swagger/models/properties/BinaryProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/DoubleProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/FloatProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/IntegerProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/LongProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PasswordProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java
Hi. I make TYPE constant is publc (RefProperty ant other classes). But I'm find method  isType(String type, String format)  I realized that doing a bike.
I'm not sure that's a good idea.
=> #1973 make TYPE and FORMAT constants public

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParam.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java, modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java
=> added type override

modules/swagger-jaxrs/pom.xml, modules/swagger-jersey-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/pom.xml, pom.xml
=> updated versions for #1798

modules/swagger-annotations/src/main/java/io/swagger/annotations/SecurityDefinition.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/Reader.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/resources/ResourceWithAnnotations.java
=> Fix misspelled method names in annotations.SecurityDefinition

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParams.java, modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/ReflectionUtilsTest.java, modules/swagger-core/src/test/java/io/swagger/reflection/Child.java, modules/swagger-core/src/test/java/io/swagger/reflection/IndirectAnnotation.java
A more complete implementation of #1867. Also fixes #1899.
=> Add support for meta-annotation processing

modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java
added file as a primitive type
=> #1319 Error log when dataType is "file" in @ApiImplicitParam (swagger-jaxrs)

modules/swagger-models/src/main/java/io/swagger/models/AbstractModel.java, modules/swagger-models/src/main/java/io/swagger/models/ExternalDocs.java, modules/swagger-models/src/main/java/io/swagger/models/License.java, modules/swagger-models/src/main/java/io/swagger/models/Operation.java, modules/swagger-models/src/main/java/io/swagger/models/Path.java, modules/swagger-models/src/main/java/io/swagger/models/Response.java, modules/swagger-models/src/main/java/io/swagger/models/Swagger.java, modules/swagger-models/src/main/java/io/swagger/models/Tag.java, modules/swagger-models/src/main/java/io/swagger/models/auth/AbstractSecuritySchemeDefinition.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractParameter.java, modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractProperty.java
Please consider adding vendorExtensions setters #2019
=> Add vendorExtensions setter #2019

modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/util/ReflectionUtilsTest.java
https://github.com/swagger-api/swagger-core/issues/2028
=> [#2028] make ReflectionUtils findMethod null safe

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/ReaderFixFor1959Test.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test1InterfaceChildResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test1InterfaceParentResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test2ClassParentResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test2InterfaceChildResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test3ClassChildResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test3ClassParentResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test4ClassChildResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/jaxrs/Test4ClassParentResource.java
Implemented corrections for pull request [1959](https://github.com/swagger-api/swagger-core/pull/1959). Please see that pull request for full details of the issues.
=> Correct pull request 1959

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithExternalDocs.java
Added support for the ExternalDocs annotation on jaxrs methods.
=> Added ExternalDocs for jaxrs methods

pom.xml
Saw tests fail with newer jackson versions
=> Jackson 2.5.5

modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java
=> fixed call to annotation type

modules/swagger-core/src/test/java/io/swagger/matchers/SerializationMatchers.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-mule/pom.xml, pom.xml
Have fixed the GenericTest issue based on details provided by @cowtowncoder in https://github.com/swagger-api/swagger-core/issues/1937
=> jackson 2.8

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
java.lang.NullPointerException:
at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:517)
at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:167)
at com.github.swagger.akka.SwaggerScalaModelConverter.resolve(SwaggerScalaModelConverter.scala:79)
at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
=> ModelConverter npe with scala based model

modules/swagger-core/src/main/java/io/swagger/jackson/JAXBAnnotationsHelper.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/XMLInfoTest.java
Creating pull request for fix for [Swagger Core Issue 2047](https://github.com/swagger-api/swagger-core/issues/2047)
=> Issue 2047

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/SwaggerSerializers.java
https://github.com/swagger-api/swagger-core/issues/1936
=> avoid unnecessary string to byte[] conversions

modules/swagger-core/src/test/java/io/swagger/parameter/ParameterSerializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java
=> added allowEmptyValue

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParam.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java, modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java, modules/swagger-core/src/test/java/io/swagger/ParameterProcessorTest.java
=> added collection format to annotations

modules/swagger-models/src/main/java/io/swagger/models/refs/GenericRef.java
=> made default constructor for proxy usage

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/util/AllowableRangeValues.java, modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java, modules/swagger-core/src/test/java/io/swagger/AllowableValuesTest.java, modules/swagger-core/src/test/java/io/swagger/ArrayPropertyDeserializerTest.java, modules/swagger-core/src/test/java/io/swagger/BeanValidatorTest.java, modules/swagger-core/src/test/java/io/swagger/ModelSerializerTest.java, modules/swagger-core/src/test/java/io/swagger/ModelWithRangesTest.java, modules/swagger-core/src/test/java/io/swagger/NumericFormatTest.java, modules/swagger-core/src/test/java/io/swagger/ParameterProcessorTest.java, modules/swagger-hibernate-validations/src/main/java/io/swagger/validator/BeanValidator.java, modules/swagger-hibernate-validations/src/test/java/io/swagger/HibernateBeanValidationsTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/ScannerTest.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/models/TestBeanParam.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/params/ChildBean.java, modules/swagger-models/src/main/java/io/swagger/models/ArrayModel.java, modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/SerializableParameter.java, modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractNumericProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/test/java/io/swagger/models/parameters/AbstractSerializableParameterTest.java, modules/swagger-models/src/test/java/io/swagger/models/properties/AbstractNumericPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/models/properties/PropertyBuilderTest.java
=> updated minimum, maximum values, default response

modules/swagger-core/src/test/java/io/swagger/ModelPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithBooleanProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/BooleanProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java
=> Added boolean enums

README.md, modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-hibernate-validations/pom.xml, modules/swagger-jaxrs/pom.xml, modules/swagger-jersey-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/pom.xml, modules/swagger-models/pom.xml, modules/swagger-mule/pom.xml, modules/swagger-servlet/pom.xml, pom.xml
=> updated versions

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/properties/ArrayPropertyDeserializerTest.java, modules/swagger-core/src/test/java/io/swagger/properties/MapPropertyDeserializerTest.java, modules/swagger-core/src/test/java/io/swagger/properties/PropertyDeserializerTest.java
=> Address classCastException in property deserializer

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/ByteConverterTest.java, modules/swagger-core/src/test/java/io/swagger/ModelSerializerTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ResourceTest1343.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/SwaggerJersey2JaxrsTest.java, modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ArrayProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/test/java/io/swagger/models/properties/PropertyBuilderTest.java
=> added uniqueItems

modules/swagger-models/src/main/java/io/swagger/models/Swagger.java
=> Add method getTag to return tag based on name

modules/swagger-core/pom.xml, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/ImmutablesGenerationTest.java, modules/swagger-core/src/test/java/io/swagger/jackson/SimpleGenerationTest.java
Possible fix for https://github.com/swagger-api/swagger-core/issues/2084
=> Respect JsonSerialiseAs

modules/swagger-core/src/test/java/io/swagger/NumericFormatTest.java
=> Make this test platform independent with CR+LFs.

modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/info/Contact.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/info/Info.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/info/License.java, modules/swagger-annotations/src/test/java/io/swagger/oas/annotations/test/info/InfoTest.java, modules/swagger-models/src/main/java/io/swagger/oas/models/info/Info.java
=> added info annotations

modules/swagger-models/pom.xml, modules/swagger-models/src/main/java/io/swagger/oas/models/responses/ApiResponse.java, modules/swagger-models/src/test/java/io/swagger/test/SimpleBuilderTest.java
=> add map for links

modules/swagger-core/src/test/java/io/swagger/SwaggerSerializerTest.java, modules/swagger-models/src/main/java/io/swagger/oas/models/links/Link.java, modules/swagger-models/src/main/java/io/swagger/oas/models/links/LinkParameter.java
=> Fixed properties

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
=> Add not null check for innerModel properties

modules/swagger-models/src/main/java/io/swagger/models/ComposedModel.java
=> Added null check to ComposedModel.setInterfaces(List<RefModel>)

modules/swagger-models/src/main/java/io/swagger/models/License.java, modules/swagger-models/src/main/java/io/swagger/models/Swagger.java, modules/swagger-models/src/main/java/io/swagger/models/Tag.java, modules/swagger-models/src/test/java/io/swagger/PojosTest.java
=> Updated equals/hashCode + updated the corresponding test

README.md, modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-hibernate-validations/pom.xml, modules/swagger-jaxrs/pom.xml, modules/swagger-jersey-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/pom.xml, modules/swagger-models/pom.xml, modules/swagger-models/src/main/java/io/swagger/models/refs/GenericRef.java, modules/swagger-mule/pom.xml, modules/swagger-servlet/pom.xml, pom.xml
=> updated dev version

modules/swagger-models/src/main/java/io/swagger/oas/models/PathItem.java
Adding getOperations and getOperationMap to PathItem Object
=> Adding readOperations and readOperationMap to PathItem Object

pom.xml
Update logback version to 1.2.3.  Reference issue #2273 
Update jackson version to 2.8.9.  Reference issue #2274
=> Update logback and jackson versions

modules/swagger-models/src/main/java/io/swagger/oas/models/media/Encoding.java
Adding extensions to Encoding Class
=> Adding extensions to Encoding Class

modules/swagger-core/src/test/resources/ModelWithSecurityRequirements.json, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/operations/AnnotatedOperationMethodTests.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/resources/UserResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/resources/data/UserData.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/resources/model/User.java, modules/swagger-models/src/main/java/io/swagger/oas/models/OpenAPI.java
Changes in the Schema definitions of Wrapper and String objects
OpenApi default version to 3.0.0
UserResource Test Added
=> Schema of String and Wrapper Objects, OpenApi version to 3.0.0

README.md
=> update 2.0 readme

modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-integration/pom.xml, modules/swagger-jaxrs2/pom.xml, modules/swagger-models/pom.xml, pom.xml
Reverts swagger-api/swagger-core#2380
=> Revert "set versions to 2.0.0-SNAPSHOT after rc"

modules/swagger-models/src/main/java/io/swagger/oas/models/headers/Header.java, modules/swagger-models/src/main/java/io/swagger/oas/models/links/Link.java, modules/swagger-models/src/main/java/io/swagger/oas/models/media/Encoding.java, modules/swagger-models/src/main/java/io/swagger/oas/models/media/Schema.java, modules/swagger-models/src/main/java/io/swagger/oas/models/parameters/Parameter.java, modules/swagger-models/src/main/java/io/swagger/oas/models/parameters/RequestBody.java
PR for issue #2326 includes #2327 .
=> Update for issue 2326 - swagger models v3

.travis.yml
https://github.com/travis-ci/travis-ci/issues/8455
=> Use openjdk7 for build due to travis-ci build issue

modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/headers/Header.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/responses/ApiResponse.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java
=> Header added to ApiResponse annotation

modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-core/src/test/java/io/swagger/matchers/SerializationMatchers.java, modules/swagger-core/src/test/resources/ModelWithSecurityRequirements.json, modules/swagger-integration/pom.xml, modules/swagger-jaxrs2/pom.xml, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/callbacks/CallbackTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/examples/ExamplesTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/parameters/ParametersTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/security/SecurityTests.java, modules/swagger-models/pom.xml, pom.xml
* updated jackson, jersey and jetty version
* clean up poms
* clean up OSGi config
=> deps versions

modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-models/src/main/java/io/swagger/oas/models/headers/Header.java, modules/swagger-models/src/main/java/io/swagger/oas/models/media/MediaType.java, modules/swagger-models/src/main/java/io/swagger/oas/models/parameters/Parameter.java
=> changing Example value from String to Object

modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/Operation.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/SecurityParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java
=> secuirtyRequirement array in Operation annotation and related logic

modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/Operation.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/annotations/encoding/EncodingTest.java, modules/swagger-models/src/main/java/io/swagger/oas/models/media/EncodingProperty.java
=> encoding annotation support

modules/swagger-core/src/main/java/io/swagger/converter/ModelConverterContextImpl.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java, modules/swagger-jaxrs2/src/test/java/io/swagger/jaxrs2/ReaderTest.java
see https://groups.google.com/d/topic/swagger-swaggersocket/893PWh5ntQk/discussion
=> fix generic model

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Content.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/ResponseContentWithArrayResource.java
refs #2397, #2497 - array schema support in Content annotation
=> refs #2397, #2497 - array schema support in Content annotation

modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/JsonDeserializationTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/serialization/properties/PropertySerializationTest.java, modules/swagger-core/src/test/resources/specFiles/oas3_2.yaml, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/examples/ExamplesTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/requests/RequestBodyTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/User.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/IntegerSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java
refs #2475 - IntegerSchema fix for long values
=> refs #2475 - IntegerSchema fix for long values

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/responses/ApiResponse.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ParameterProcessor.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/SimpleUserResource.java
refs #2410 - return type resolving in response
=> refs #2410 - return type resolving in response

modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java
=> refs #2410 - fix test

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java
refs #2515 - fix securityschemes from client overwritten
=> refs #2515 - fix securityschemes from client overwritten

modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverterContextImpl.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/AbstractModelConverter.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SwaggerAnnotationIntrospector.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/TypeNameResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/PojoTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ApiFirstRequiredFieldModel.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ModelWithAltPropertyName.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ModelWithApiModel.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ModelWithTuple2.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/XmlFirstRequiredFieldModel.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/composition/AbstractModelWithApiModel.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/GenericResponsesResource.java
refs #2522 - fix schema name resolving
=> refs #2522 - fix schema name resolving

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Hidden.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SwaggerAnnotationIntrospector.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/HiddenAnnotatedUserResource.java
refs #2526 - add @Hidden annotation support
=> refs #2526 - add @Hidden annotation support

modules/swagger-models/src/main/java/io/swagger/models/Info.java
Fix for https://github.com/swagger-api/swagger-core/issues/2486
=> Added setVendorExtensions() in Info

modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverters.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/GenericResponsesResource.java
fix #2531 - fix  value in content schema implementing class with overridden name
=> fix #2531 - fix  value in content schema implementing class with overridden name

modules/swagger-jaxrs2-servlet-initializer/pom.xml, modules/swagger-jaxrs2/pom.xml, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/AbstractAnnotationTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/it/OpenApiResourceIT.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/it/model/Widget.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/it/resources/WidgetResource.java, modules/swagger-jaxrs2/src/test/webapp/WEB-INF/web.xml, pom.xml
refs #2521 - dynamic jetty port and integration tests
=> refs #2521 - dynamic jetty port and integration tests

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/DefaultParameterExtension.java
code that was deprecated in jackson 2.9.x
=> Rework code that uses deprecated Jackson methods (2.0 branch)

modules/swagger-models/src/main/java/io/swagger/models/properties/BooleanProperty.java, modules/swagger-models/src/test/java/io/swagger/BooleanPropertyTest.java
=> Ensure default empty string is set as Null on BooleanProperty

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/ResponsesResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/MultipleBaseBean.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/MultipleSub1Bean.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/MultipleSub2Bean.java
ref #2579 - fixed composition support in schema
=> ref #2579 - fixed composition support in schema

modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverter.java, modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverterContext.java, modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverterContextImpl.java, modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverters.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/AbstractModelConverter.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/ModelConverterTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/CustomConverterTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/SamplePropertyConverter.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/SnakeCaseConverterTest.java
refs #2593 - Phase 1: merge orverlapping resolveAnnotatedType methods, property invoke container chain, minor fixes
=> refs #2593 - Phase 1: merge orverlapping resolveAnnotatedType methods, property invoke container chain, minor fixes

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java
=> Make Reader and ServletConfig fields protected in BeanConfig

modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java
Response Fix. There was a test failing for that.
=> ReaderTest Response Bugfix

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/ext/AbstractOpenAPIExtension.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/ext/OpenAPIExtension.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/util/ReaderUtils.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/NoPathSubResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/ResourceWithSubResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/SubResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/SubResourceHead.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/SubResourceTail.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Test2607.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/TestResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/TestSub2607.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/TestSubResource.java
refs #2607 - implement subresource resolving
=> refs #2607 - implement subresource resolving

modules/swagger-core/src/main/java/io/swagger/v3/core/filter/SpecFilter.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ModelDeserializer.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/ModelConverterTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/properties/MapPropertyDeserializerTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/ContainerTest.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java, modules/swagger-models/src/test/java/io/swagger/test/SchemaTests.java
refs #2461 - additionalProperties as Boolean or Schema
=> refs #2461 - additionalProperties as Boolean or Schema

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/TypeNameResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/ModelConverterTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/PojoTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/composition/Thing3.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/ComposedSchemaTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/InheritedBeanTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/resources/TestObjectTicket2620.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/resources/TestObjectTicket2620Subtypes.java, modules/swagger-core/src/test/resources/AbstractBaseModelWithoutFields.json
refs #2620, #2619 - fix polymorphic schemas resolving
=> refs #2620 - fix polymorphic schemas resolving

.mvn/wrapper/maven-wrapper.properties
Has some logging improvements, eg colours.
=> maven 3.5.2

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/encoding/EncodingTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/requests/RequestBodyTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/security/SecurityTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/BookStoreTicket2646.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/extensions/ExtensionsResource.java, modules/swagger-jaxrs2/src/test/resources/petstore/FullPetResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/SecurityResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/operation/ExternalDocumentationResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/operation/OperationResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/operation/SubResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/parameters/MultipleNotAnnotatedParameter.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/requestbody/RequestBodyMethodPriorityResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/requestbody/RequestBodyParameterPriorityResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/requestbody/RequestBodyResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/tags/CompleteTagResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/tags/TagMethodResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/tags/TagOperationResource.yaml
=>  Fixes #2646

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/reflection/ReflectionUtilsTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Ticket2644AnnotatedInterface.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Ticket2644ConcreteImplementation.java
refs #2644 -  2.0 issue/interface annotation inheritance
includes and replaces #2645
=> refs #2644 -  2.0 issue/interface annotation inheritance

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java
fix skipping non jax-rs resource methods, refs https://groups.google.com/forum/#!topic/swagger-swaggersocket/33654b1CROo
=> reader - fix skipping non jax-rs resource methods

modules/swagger-jaxrs/src/test/java/io/swagger/SubResourceReaderTest.java
=> refs #2433 - fix tests

pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.4
=> jackson 2.9.4 (2.0 branch)

modules/swagger-core/src/test/java/io/swagger/ModelSerializerTest.java, modules/swagger-models/src/main/java/io/swagger/models/AbstractModel.java, modules/swagger-models/src/main/java/io/swagger/models/ArrayModel.java, modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java, modules/swagger-models/src/main/java/io/swagger/models/Xml.java
=> refs #2669 - move xml schema property to AbstractModel

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/properties/PropertyDeserializerTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java
refs #2316 - Inner properties may have XML declared
includes and replaces #2674 and #2313
=> refs #2316 - Inner properties may have XML declared

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiOperation.java, modules/swagger-jaxrs/src/test/java/io/swagger/AllowUsingApiOperationOnTypeTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ApiOperationResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/Uber.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/extensions/AllowUsingApiOperationOnTypeTest.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/resources/ApiOperationResource.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/resources/Uber.java
Solution for the issue: 
https://github.com/swagger-api/swagger-core/issues/2652
=> ElementType.TYPE added to the ApiOperation, Test Added

modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/Parameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/SerializableParameter.java
Property allowEmptyValue reubicated. 
Solving this Issue: https://github.com/swagger-api/swagger-core/issues/2492
=> refs #2492 - Relocate Parameter allowEmptyValue

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ClassPathParentResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ClassPathSubResource.java
=> refs #2632 - Path in Class level removed for subresources

modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/ApiListingResourceIT.java
=> Fix newline errors for tests on Windows

modules/swagger-core/src/test/java/io/swagger/v3/core/converting/NumericFormatTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/properties/MapPropertyDeserializerTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/TestUtils.java
=> Fix newline errors for tests on Windows for 2.0

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/OpenApiConfigurationLoader.java
StringBuffer is synchronized.
Travis builds are failing intermittently but this change passes consistently when I run on my laptop.
=> use StringBuilder in ModelResolver

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/util/ReaderUtils.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/PetResourceSlashesinPath.java
=> refs #2751 - fix path building for resources without leading slashes

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/MyClass.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/MyOtherClass.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/MySuperClass.java
=> refs #2635 - Testing XML Naming with is prefix in Models in Master

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/JaxbObjectMapperFactory.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/MyClass.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/MyOtherClass.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/MySuperClass.java
=> refs #2635 - Testing XML Naming with is prefix in Models

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/EnumPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithEnumField2707.java, modules/swagger-core/src/test/java/io/swagger/models/TestEnum2707.java
refs #2707 - fix name resolution in enums. Includes and replaces #2712
=> refs #2707 - fix name resolution in enums

modules/swagger-models/src/main/java/io/swagger/models/Operation.java, modules/swagger-models/src/test/java/io/swagger/models/OperationTest.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ServletReaderExtension.java
Replaces #2782, allows setting operation deprecated to false
=> refs #2782 - allows setting operation deprecated to false

modules/swagger-servlet/src/main/java/io/swagger/servlet/config/ServletScanner.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/config/WebXMLReader.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ReaderExtensions.java, modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ServletReaderExtension.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/resources/ResourceWithAnnotations.java
=> Code fixes in swagger-server

modules/swagger-core/pom.xml, modules/swagger-hibernate-validations/pom.xml, modules/swagger-jaxrs/pom.xml, modules/swagger-jersey-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/pom.xml, modules/swagger-models/pom.xml, modules/swagger-mule/pom.xml, modules/swagger-servlet/pom.xml, pom.xml
Moved project dependencies' versions to parent pom
=> Moved project dependencies' versions to parent pom

modules/swagger-core/src/main/java/io/swagger/core/filter/AbstractSpecFilter.java, modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/DefinitionAllowedFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/filteredDefinition.json
=> Refs #2809 - Allows filtering of specific definitions in SpecFilter.

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SwaggerAnnotationIntrospector.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Ticket2848Resource.java
refs #2848 - fix required resolving for arrayschema schema
=> refs #2848 - fix required resolving for arrayschema schema

modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java, modules/swagger-models/src/test/java/io/swagger/models/parameters/AbstractSerializableParameterTest.java
=> checking empty string in examples #2783

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/ComposedPropertyTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ComposedProperty.java
=> #2621 Basic implementation of 'allOf' for properties.

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/DefaultParameterExtension.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/ResolvedParameter.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/FormParamBeanTest.java
This fixes issue #2985, Added support for @BeanParam 's containing @FormParam properties.
=> Form param bean param fix

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/headers/Header.java, modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Content.java, modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Encoding.java, modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/ExampleObject.java, modules/swagger-core/src/test/resources/specFiles/oas3.yaml, modules/swagger-core/src/test/resources/specFiles/petstore-3.0-referred-schemas.json, modules/swagger-core/src/test/resources/specFiles/petstore-3.0-v2.json, modules/swagger-core/src/test/resources/specFiles/petstore-3.0-v2_withoutModels.json, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/PetResourceTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/petstore/PetResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/PetResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/PetResourceSlashesinPath.java, modules/swagger-jaxrs2/src/test/resources/petstore/FullPetResource.yaml
This pull request fixes the minor typos detected by https://github.com/client9/misspell
=> Fix typo detected by github.com/client9/misspell

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/rs/AbstractEntityRestService.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/rs/EntityRestService.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/rs/PersistentDTO.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/rs/ProcessTokenDTO.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/rs/ProcessTokenRestService.java
=>  ref #3082 - updated returnType handling

modules/swagger-core/src/main/java/io/swagger/v3/core/util/PrimitiveType.java
Also alphabetized the classes in the parameter list.
=> Serialize org.joda.time.LocalDateTime as a string

modules/swagger-gradle-plugin/build.gradle
=> Cleanup Gradle plugin buildscript classpath

README.md
Readme Update - Security Section Added
=> Readme Update - Security Section Added

README.md
Adding Jenkins Status Build Badges for Java 8 and Java 9 to Master branch.
=> Add Jenkins Status Build Badges

pom.xml
Jackson Version Updated to 2.9.9
=> Jackson update to 2.9.9

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket2189Test.java
The current class was being considered when resolving the subtypes.
=> fix #2189 - remove current class from JsonSubTypes

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3348Test.java
=> refs #3348 - clone all resolved properties

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/EnumPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ModelWithEnumRefProperty.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/TestSecondEnum.java
=> refs #3124 - enums as ref

modules/swagger-annotations/src/main/java/io/swagger/annotations/ExtensionProperty.java, modules/swagger-core/src/main/java/io/swagger/util/BaseReaderUtils.java, modules/swagger-core/src/test/java/io/swagger/BaseReaderUtilsTest.java
PR to go with issue https://github.com/swagger-api/swagger-core/issues/3375
=> Update extension properties to support parse value (openAPI)

modules/swagger-core/src/main/java/io/swagger/v3/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/v3/core/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/petstore-3.0-v2-ticket-3303.json
=> refs #3345 - Include discriminator mapped schemas when filtering

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java
=> Fix typo in AnnotationsUtils; Fixes #3423

pom.xml
=> Classgraph 4.8.65

modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-integration/pom.xml, modules/swagger-jaxrs2-servlet-initializer/pom.xml, modules/swagger-jaxrs2/pom.xml, modules/swagger-jaxrs2/src/test/resources/logback-test.xml, modules/swagger-maven-plugin/pom.xml, modules/swagger-maven-plugin/src/test/resources/logback-test.xml, modules/swagger-models/pom.xml, pom.xml
includes and replaces #3445, #3430
=> Refs #3399, #3445 Change javax to jakarta artifact dependencies, relax OSGI import

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/AnnotationsUtilsTest.java
includes and replaces #3112 and #3114
=> refs #3111 - fix Schema.implementation processing for primitive types

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReaderUtils.java
For 1.5 branch...
We use the same approach / code base as used by the current master branch.
Fixes: https://github.com/swagger-api/swagger-core/issues/3367
=> swagger-jaxrs: fix path building

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/ReaderListener.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/ReaderListenerResource.java
overall the purpose of this pull request is to make it easier to extend the Reader class which enables control / customization of the processes within.
Closes #3517
=> Utilize the OpenApiReader interface in ReaderListener method signatures

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java
Closes #2887 
Corrects Schema.AccessMode.READ_ONLY description
=> Ref #2887 Update Schema.AccessMode.READ_ONLY docs

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/resources/petstore/FullPetResource.yaml
=> refs #3500 - fix @Deprecated processing

README.md, modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-gradle-plugin/gradle.properties, modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/SwaggerPlugin.java, modules/swagger-integration/pom.xml, modules/swagger-jaxrs2-servlet-initializer-v2/pom.xml, modules/swagger-jaxrs2-servlet-initializer/pom.xml, modules/swagger-jaxrs2/pom.xml, modules/swagger-maven-plugin/pom.xml, modules/swagger-models/pom.xml, pom.xml
* refs #3608 - fix maven plugin with maven < 3.5
* bump snapshot 2.1.4-SNAPSHOT
=> refs #3608 - fix maven plugin with maven < 3.5 - bump snaphsots

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
This fixes https://github.com/swagger-api/swagger-core/issues/3605
=> Fixed potential NPE in io.swagger.jackson.ModelResolver._addEnumProps()

.github/workflows/prepare-release.yml
Reverts swagger-api/swagger-core#3654
=> Revert "Automation - temporarily add test environment variables"

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/reflection/ReflectionUtilsTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket2144/BaseDTO.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket2144/BaseResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket2144/Item.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket2144/ItemResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket2144/ItemWithChildren.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/AggregateEndpoint.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/FirstEndpoint.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/MainResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/OriginalEndpoint.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/SampleDTO.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/SampleOtherDTO.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3149/SecondEndpoint.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3426/Parent.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3426/Ticket3426Resource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694Resource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceExtendedType.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceInterface.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceInterfaceExtendedType.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceInterfaceSimple.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceInterfaceSimpleSameReturn.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceSimple.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/generics/ticket3694/Ticket3694ResourceSimpleSameReturn.java
refs #2144, refs #3149, refs #3426, refs #3694
fixes overridden generic resources methods (possibly limited to identified scenarios in referenced tickets)
=> refs #2144, refs #3149, refs #3426, refs #3694 - fix overridden generic resources methods

README.md
Updating the badge for swagger-core-1.5
=> Updating Badge

modules/swagger-maven-plugin/pom.xml
Upgrade Junit dependency from 4.12 to 4.13.1
=> bump junit deps

modules/swagger-models/src/main/java/io/swagger/models/utils/PropertyModelConverter.java
add xml to property in ModelToPropertyConverter.
=> add xml to property

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
I just noticed a small typo in the code when debugging
=> Typo in ModelResolver

modules/swagger-core/src/main/java/io/swagger/v3/core/util/DeserializationModule31.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/SecurityScheme31Deserializer.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/SecuritySchemeDeserializer.java, modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/OpenAPI3_1DeserializationTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/serialization/OpenAPI3_1SerializationTest.java, modules/swagger-core/src/test/resources/specFiles/3.1.0/petstore-3.1_sample.yaml
=> updated securityscheme deserialization class

modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/SchemaDeserializationTest.java, modules/swagger-core/src/test/resources/specFiles/3.1.0/petstore-3.1_refs_siblings.yaml
added tests to check that ref property is deserialized along other schema properties.
=> Schema Deserialization Tests

pom.xml
add dependency to check during build time the security vulnerabilities of the project.
=> add org.owasp dependency for master

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3853Test.java
replaces #4141 and includes its test case
=> refs #3853- fix composed schemas ref with fqn TypeNameResolver

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/PojoTest.java
Addressing issue #4049 where pattern is not picked up for `List<String>`
Added tested to verify
=> Set regex pattern on array

modules/swagger-core/src/test/java/io/swagger/v3/core/converting/PojoTest.java
I have added a test with booleans (Boolean object and boolean type) to verify yml generation
=> PojoTest: add test with booleans

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/enums/SecuritySchemeType.java
Add missing mutualTLS type for securitySchema.
=> Fix : Add missing mutualTLS

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
=> Remove System.err

modules/swagger-annotations/pom.xml, modules/swagger-core/pom.xml, modules/swagger-eclipse-transformer-maven-plugin/pom.xml, modules/swagger-gradle-plugin/build.gradle, modules/swagger-integration/pom.xml, modules/swagger-jaxrs2-servlet-initializer-v2/pom.xml, modules/swagger-jaxrs2-servlet-initializer/pom.xml, modules/swagger-jaxrs2/pom.xml, modules/swagger-maven-plugin/pom.xml, modules/swagger-models/pom.xml, modules/swagger-project-jakarta/modules/swagger-annotations-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-annotations-jakarta/transformed/README.md, modules/swagger-project-jakarta/modules/swagger-core-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-core-jakarta/transformed/README.md, modules/swagger-project-jakarta/modules/swagger-integration-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-integration-jakarta/transformed/README.md, modules/swagger-project-jakarta/modules/swagger-jaxrs2-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-jaxrs2-jakarta/transformed/README.md, modules/swagger-project-jakarta/modules/swagger-jaxrs2-servlet-initializer-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-jaxrs2-servlet-initializer-jakarta/transformed/README.md, modules/swagger-project-jakarta/modules/swagger-jaxrs2-servlet-initializer-v2-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-jaxrs2-servlet-initializer-v2-jakarta/transformed/README.md, modules/swagger-project-jakarta/modules/swagger-maven-plugin-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-models-jakarta/pom.xml, modules/swagger-project-jakarta/modules/swagger-models-jakarta/transformed/README.md, modules/swagger-project-jakarta/pom.xml, pom.xml
refs #4485
refs #4354
refs #4090 (this PR also adds sources and javadoc artifacts)
=> switch to original eclipse transformer for jakarta artifacts -  update dependencies

modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverters.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/ModelConverterTest.java
=> Skip groovy.lang package in ModelConverters

modules/swagger-core/pom.xml
=> Add JAX-RS v2.2 tolerance by swagger-core

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ParameterProcessor.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/parameters/ParametersTest.java, modules/swagger-jaxrs2/src/test/resources/petstore/FullPetResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/parameters/ArraySchemaResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/parameters/Parameters31Resource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/parameters/ParametersResource.yaml, modules/swagger-jaxrs2/src/test/resources/petstore/parameters/RepeatableParametersResource.yaml
=> Fix isExplode method and explode tests

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket4760Test.java
=> refs-#4760-Fix enum type annotations processing

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/util/ReaderUtils.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Ticket4878Resource.java
=> refs #4878 - fix model resolution for global path parameters with openAPI 3.1

modules/swagger-gradle-plugin/README.md, modules/swagger-gradle-plugin/build.gradle, modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/SwaggerPlugin.java, modules/swagger-project-jakarta/pom.xml, pom.xml
Update common lang3 dependency to 3.18
Fixes:
=> chore: update common lang3 to 3.18

modules/swagger-project-jakarta/pom.xml, pom.xml
=> Bump github classgraph version to 4.8.181
