swagger-api/swagger-core

modules/swagger-models/src/main/java/com/wordnik/swagger/models/parameters/RefParameter.java
Fixing RefParameter logic to use '#/parameters' instead of '#/definitions'
=> Fixing RefParameter logic

modules/swagger-core/src/test/scala/auth/AuthSerializationTest.scala, modules/swagger-core/src/test/scala/parameter/ParameterSerializationTest.scala
Only YAML tests were impacted because only YAML tests (as of now) were
using multi-line strings for comparison.  The approach taken was to
convert the object under test to an ObjectNode, read the multi-line
YAML into an ObjectNode and then use "should equal" for comparison.
This would make #822 unnecessary and could be used in the future to create a test utility for testing real objects instead of string outputs.
=> Fix tests on Windows

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/utils/ParameterUtils.java, modules/swagger-jersey2-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/SwaggerJersey2Jaxrs.java, modules/swagger-jersey2-jaxrs/src/test/scala/SwaggerJersey2JaxrsTest.scala, modules/swagger-jersey2-jaxrs/src/test/scala/params/BaseBean.java, modules/swagger-jersey2-jaxrs/src/test/scala/params/ChildBean.java, modules/swagger-jersey2-jaxrs/src/test/scala/params/RefBean.java
* @BeanParam is a JAX-RS 2.0 thing and not specific to Jersey 2 but
until swagger-core has a JAX-RS 2.0 module, it makes sense to be here
and we can break this logic out when that time comes
Fixes #543
=> Add support for @BeanParam to Jersey 2

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java
DefaultParameterExtension imports both java.lang.reflect.* and com.wordnik.swagger.models.parameters.* making the correct package for class Parameter ambiguous. java.lang.reflect.* is not required so remove it to fix compilation.
=> Fix complication of DefaultParameterExtension

README.md
The naming of the milestone (1.5 instead of 1.5.0) is a bit... meh.. but the link itself is now working.
=> Fixed link to 1.5 milestone.

modules/swagger-core/src/test/scala/1_3/converter/BoxedTypesTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ByteConverterTest.scala, modules/swagger-core/src/test/scala/1_3/converter/CovariantGetterTest.scala, modules/swagger-core/src/test/scala/1_3/converter/EnumConversionPropertyTest.scala, modules/swagger-core/src/test/scala/1_3/converter/JsonIgnoreModelTest.scala, modules/swagger-core/src/test/scala/1_3/converter/JsonIgnorePropertiesModelTest.scala, modules/swagger-core/src/test/scala/1_3/converter/JsonPropertyModelTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ModelConversionTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ModelPropertyParserTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ModelPropertyTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ModelWithOptionalFieldsTest.scala, modules/swagger-core/src/test/scala/1_3/converter/PropertyAnnotationTest.scala, modules/swagger-core/src/test/scala/1_3/converter/SnakeCaseConverterTest.scala, modules/swagger-core/src/test/scala/CompositionTest.scala, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-core/src/test/scala/ScalaModelTest.scala, modules/swagger-core/src/test/scala/ScalaTest.scala, modules/swagger-core/src/test/scala/auth/AuthSerializationTest.scala, modules/swagger-core/src/test/scala/matchers/SerializationMatchers.scala
The json serialization tests are failing for me on windows.  Looking through previous issues the method described in pull request #831 looks to alleviate a lot of the issues with cross platform line endings.
Added some helpers since it was used in a lot of tests.
=> get tests to run on windows by using method described by whitlockjc

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java
@fehguy Please have a look when you get a chance. It's an extremely minor fix but the server logs were really getting overloaded by the following message after your bug fix for #937 :
INFO  [2015-03-29 08:11:50,664] org.reflections.Reflections: Reflections took 81 ms to scan 1 urls, producing 22 keys and 41 values 
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
=> Removing System.out.println from a previous bugfix under #937

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/BeanConfig.java, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/SimpleResourceWithoutAnnotations.java
Hey guys,
Resubmitting https://github.com/swagger-api/swagger-core/pull/797 against Swagger 1.5.
While working on JAX-RS applications, I have run into the issues that Swagger has a bit limited support of the native JAX-RS services/resources which do not use @ApiXxx annotations, however the most of required implementation is already there, in Swagger JAX-RS module. 
The small change in BeanConfig allows to introspect not only @Api - annotated classes but @Path - annotated ones as well. When used with Reader, the @ApiXxx annotations are not required anymore. . 
The tests have been added to confirm that the proper JAX-RS API description is being built (without any @ApiXxx annotations) for native JAX-RS service/resource.
I think these small changes allow to integrate Swagger into existing …
=> Enhanced BeanConfig to support @Path JAX-RS resources and fixed Reader operations recognition.

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/AbstractModelConverter.java, modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/SwaggerAnnotationIntrospector.java, modules/swagger-core/src/test/scala/CompositionTest.scala, modules/swagger-core/src/test/scala/models/composition/AbstractBaseModelWithoutFields.java, modules/swagger-core/src/test/scala/models/composition/Thing3.java
Since the method findSubtypes was not implemented after jackson-swagger-module had been moved to the  swagger-core, ModelConverter could not find subtypes of passed class. Fixed it. Added unit-test.
=> Fix for #847. Implemented findSubtypes.

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java, modules/swagger-jaxrs/src/test/scala/ReferenceTest.scala, modules/swagger-jaxrs/src/test/scala/models/CategoryWithApiModel.java, modules/swagger-jaxrs/src/test/scala/models/Pet.java
References names have been set wrong if referenced classes are annotated by ApiModel with different names. Fixed.
=> Fixed #992. Fixed references processing with ApiModel.

modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java
Fixes #942: Path validation has been fixed.
Initial fix [#1008](https://github.com/swagger-api/swagger-core/pull/1008) was incorrect as `parentPath` never gets null value.
=> Fixes #942: Path validation has been fixed.

modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiOperation.java, modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiResponse.java, modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithApiOperationCode.java, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithApiResponseResponseContainer.java
Based on [#1017](https://github.com/swagger-api/swagger-core/pull/1017)
Fixes #954 Support "array" and "set" as @ApiOperation#responseContainer value
=> Array and set support

modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/scala/1_3/converter/BoxedTypesTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ByteConverterTest.scala, modules/swagger-core/src/test/scala/1_3/converter/CovariantGetterTest.scala, modules/swagger-core/src/test/scala/1_3/converter/EnumConversionPropertyTest.scala, modules/swagger-core/src/test/scala/1_3/converter/JsonIgnoreModelTest.scala, modules/swagger-core/src/test/scala/1_3/converter/JsonIgnorePropertiesModelTest.scala, modules/swagger-core/src/test/scala/1_3/converter/JsonPropertyModelTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ModelConversionTest.scala, modules/swagger-core/src/test/scala/1_3/converter/ModelPropertyTest.scala, modules/swagger-core/src/test/scala/1_3/converter/PropertyAnnotationTest.scala, modules/swagger-core/src/test/scala/1_3/converter/SnakeCaseConverterTest.scala, modules/swagger-core/src/test/scala/CompositionTest.scala, modules/swagger-core/src/test/scala/GuavaTest.scala, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-core/src/test/scala/ModelSerializerTest.scala, modules/swagger-core/src/test/scala/ScalaModelTest.scala, modules/swagger-core/src/test/scala/ScalaTest.scala, modules/swagger-models/src/main/java/com/wordnik/swagger/models/ModelImpl.java
Fixes #1057: 'type' property was set to 'object' for model schema.
=> Fixes #1057: 'type' property was set to 'object' for model schema.

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/DefaultParameterExtension.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jersey2-jaxrs/src/test/scala/ScannerTest.scala, modules/swagger-jersey2-jaxrs/src/test/scala/models/TestBeanParam.java, modules/swagger-jersey2-jaxrs/src/test/scala/resources/ResourceWithBeanParams.java, modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java
Fixed #970: DefaultValue missing in post body of swagger.json in 1.5.3-M1
* Supports `@DefaultValue` annotation for `BodyParameter`
* Annotations handling was made order insensitive
=> Fixed #970: DefaultValue missing in post body of swagger.json in 1.5.3-M1

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-core/src/test/scala/io/swagger/jackson/EnumTest.java, modules/swagger-core/src/test/scala/models/ModelWithTuple2.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/DefaultParameterExtension.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/resources/ResourceWithTypedResponses.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, pom.xml
Fixed #1120: Models handling has been reworked.
Actually the #1120 has to separate issues. The first one that swagger doesn't fill the [Response.schema](https://github.com/swagger-api/swagger-core/blob/6875dfe0cc5e7f3ec08e49f4d0eb9c5e6832bfd3/modules/swagger-models/src/main/java/io/swagger/models/Response.java#L11) property for primitive types and the second that `URL` class is treated as complex type `"$ref" : "#/definitions/string"` (https://github.com/swagger-api/swagger-core/issues/1120#issue-83516910) while it should be reported as a primitive `string` with the `url` format.
The first issue rises here https://github.com/swagger-api/swagger-core/blob/6875dfe0cc5e7f3ec08e49f4d0eb9c5e6832bfd3/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L820-840 - primitive types are …
=> Fixed #1120: Models handling has been reworked.

modules/swagger-core/src/main/java/io/swagger/converter/ModelConverterContext.java, modules/swagger-core/src/main/java/io/swagger/converter/ModelConverterContextImpl.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/scala/1_3/converter/SnakeCaseConverterTest.scala, modules/swagger-jaxrs/src/test/scala/ReferenceTest.scala, modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala, modules/swagger-jaxrs/src/test/scala/models/ModelWithReference.java, modules/swagger-jaxrs/src/test/scala/models/SubModelWithSelfReference.java
Properly resolve a inner model with a self/cyclic reference.
In the following example the implementation was lacking to generate a property reference from Model B to Model B.
[Model A] -> [Model B] -> [Model B]
I extented the 'ReferenceTest ' to cover this situation.
=> [Develop_2.0] Properly resolve a inner model with a self/cyclic references

modules/swagger-core/pom.xml, modules/swagger-core/src/test/java/io/swagger/BeanValidatorTestNG.java, modules/swagger-hibernate-validations/pom.xml, modules/swagger-jaxrs/pom.xml, modules/swagger-jersey2-jaxrs/pom.xml, pom.xml
- Added configuration for the TestNG
- Created sample test
=> Fixed #1203: Migrate tests from the Scala to the plain Java

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java
Make sure the access field in an @ApiParam annotation gets copied to BodyParam.
=> Make sure access field is populated when constructing BodyParam obj

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jaxrs/src/test/java/io/swagger/CollectionFormatTest.java, modules/swagger-jaxrs/src/test/scala/GenericsTest.scala, modules/swagger-jaxrs/src/test/scala/resources/CollectionFormatResource.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/FormParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/QueryParameter.java
Fixes #1160: CollectionFormat default value for form and query parameters has been changed to multi
=> Fixes #1160: CollectionFormat default value for form and query parameters has been changed to multi

modules/swagger-core/src/main/java/io/swagger/util/ModelDeserializer.java
Fixes swagger-api/swagger-codegen#980
In swagger-codegen, a model which inherit from an other without defining its own properties will result in a NullPointerException. The error is caused by the ModelDeserializer which create a CompoundModel without any parent.
This fix would allow such a case.
=> Fixes swagger-api/swagger-codegen#980 : Allowing inheritance without additonal properties

modules/swagger-core/src/main/java/io/swagger/jackson/AbstractModelConverter.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java, modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java, modules/swagger-core/src/test/scala/ModelConverterTest.scala, modules/swagger-core/src/test/scala/models/ModelWithNumbers.java, modules/swagger-models/src/main/java/io/swagger/models/properties/BaseIntegerProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/BooleanProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/DecimalProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/DoubleProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/FloatProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/IntegerProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/LongProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/main/java/io/swagger/models/properties/StringProperty.java
Fixed #1154: Handling of BigDecimal and BigInteger classed has been improved.
Mapping of a small set of "well-known" classes into Swagger properties is implemented via hard-coded string identifiers of supported types. These string identifiers are defined in two classes: [TypeNameResolver](https://github.com/swagger-api/swagger-core/blob/cfd8eda836da8bd49b117259099d914b6ad4b19b/modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java#L48-78) and [AbstractModelConverter](https://github.com/swagger-api/swagger-core/blob/cfd8eda836da8bd49b117259099d914b6ad4b19b/modules/swagger-core/src/main/java/io/swagger/jackson/AbstractModelConverter.java#L91-121). This approach has two main drawbacks:
1. String identifiers have to be synchronized between two classes;
2. String …
=> Fixed #1154: Handling of BigDecimal and BigInteger classed has been improved.

modules/swagger-jersey-jaxrs/pom.xml, modules/swagger-jersey-jaxrs/src/main/java/io/swagger/jersey/SwaggerJerseyJaxrs.java, modules/swagger-jersey-jaxrs/src/test/java/io/swagger/FormDataBodyPartTest.java, modules/swagger-jersey-jaxrs/src/test/java/io/swagger/resources/ResourceWithFormData.java
Fixes #1187: FormDataBodyPart is set as ignored during generating the Swagger
=> Fixes #1187: FormDataBodyPart is set as ignored during generating the Swagger

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java
When looking for overridden methods, if the superclass or interface that is being used has overloaded methods with the same name, an IndexOutOfBoundsException will be generated (on line 93 in old code), because the code  is not checking for the array lengths and using the length of the methodToFind.getParameterTypes to iterate arrays of different length.
=> Fix IndexOutOfBoundsException in ReflectionUtils

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java
Currently, parameters that have @Context annotation are ignored by the Reader. This is fine for automatically processed parameters, but with Vendor Extensions, it would be nice to be able to extend the model with additional parameter information for these parameters.
=> Allow VendorExtensions to process @Context params

modules/swagger-models/pom.xml, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/test/java/io/swagger/models/properties/PropertyBuilderTest.java
The [`PropertyBuilder.build(String, String, Map<PropertyId, Object>`)](https://github.com/swagger-api/swagger-core/blob/bbca9a657704d32348852b4c9a658a4923e48d82/modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java#L25) call doesn't set format value for string properties. So, when we parse JSON with the following property definition:
```
"someProperty" : {
"type" : "string",
"format" : "url"
}
```
we get this output:
```
"someProperty" : {
"type" : "string"
}
```
Proposed PR fixes this issue.
=> 'format' handling has been fixed.

modules/swagger-models/src/main/java/io/swagger/models/properties/ArrayProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/BooleanProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/DoubleProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/FloatProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/IntegerProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/LongProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/MapProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/StringProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/UUIDProperty.java, modules/swagger-models/src/test/java/io/swagger/ArrayPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/BooleanPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/DoublePropertyTest.java, modules/swagger-models/src/test/java/io/swagger/FloatPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/IntegerPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/LongPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/MapPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/RefPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/StringPropertyTest.java, modules/swagger-models/src/test/java/io/swagger/UUIDPropertyTest.java
Fixes #1331: StringProperty.equals(Object) has been fixed. Also equals() method was fixed for all AbstractProperty's descendants, which overrides it.
=> Fixes #1331: StringProperty.equals(Object) has been fixed

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/util/JsonDeserializationTest.java, modules/swagger-core/src/test/resources/specFiles/propertyWithVendorExtensions.json, modules/swagger-models/src/main/java/io/swagger/models/Model.java, modules/swagger-models/src/main/java/io/swagger/models/RefModel.java, modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/Property.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java
I forgot to add a vendor extension getter to the Model and Property interfaces. Without these it makes it annoying to write code that deals with vendor extensions because you must first cast to a AbstractModel/AbstractProperty to access the vendor extensions map.
Additionally, I did not account for the complexity of deserializing Properties (i.e. PropertyDeserializer and PropertyBuilder). As such, I had to add some logic to both classes to support deserializing vendor extensions. Please let me know if you know of a cleaner way of supporting this. 
Finally, I added deserialization test for a Property with vendor extensions. 
As always feedback on my code is appreciated.
=> Additional Vendor Extensions upgrades

README.md
I was disappointed when I finally discover after some time that an up to date but not linked documentation exists to [setup swagger 1.5.x](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-JAX-RS-Project-Setup-1.5.X).
This pull request only does one thing: update link url to last version of the documentation.
This defect can also be seen on the [getting started > overview page of swagger.io](http://swagger.io/getting-started).
=> link to last setup jaxrs page: 1.5.X instead of legacy 1.3.X

modules/swagger-core/pom.xml, modules/swagger-jaxrs/pom.xml
This is a PR for making the above jars into OSGI-bundles.
The next steps are:
- adding an integration test to somewhere (in another test specific component)
- adding a separate artifact that generates its karaf feature definition so that we don't need to install individual depending bundles.
Any suggestion appreciated.
regards, aki
=>  #1361 Making swagger-core and swagger-jaxrs OSGi-enabled

modules/swagger-core/src/test/java/io/swagger/model/override/OverrideTest.java
The syntax for the test method is:
`assertEquals(expected, actual);`
Swapping them around make no difference to whether the test will pass of fail, it just makes understanding it clearer if it ever fails. Eg, it will say something like:
`Expected "error" but was "string"`
when it should have been:
`Expected "string" but was "error"`
=> 'expected' and 'actual' wrong way around

modules/swagger-models/src/main/java/io/swagger/models/ComposedModel.java
This references issue 1277 https://github.com/swagger-api/swagger-core/issues/1277. 
Need this to fix an issue with the use of added in SwaggerSpecFilter caused a NullPointerException when using jackson sub types (https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L494).
=> Adding in a clone method.

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/GenericsTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/generics/AbstractEntity.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/generics/ApiCrudRoute.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/generics/UserApiRoute.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/generics/UserEntity.java
Fixes #1344: Scanning model with Generic Type has been fixed
=> Fixes #1344: Scanning model with Generic Type has been fixed

modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/SwaggerJersey2JaxrsTest.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/resources/ResourceWithFormData.java
Fixes #1387: FormDataContentDisposition and FormDataBodyPart are set ignored for jersey2. Also 'else' branch was added to process FormDataParam, so now all FormDataParam will be processed  as FormParameter (not only InputStream type)
=> Fixes #1387: FormDataContentDisposition and FormDataBodyPart are set ignored for jersey2

modules/swagger-annotations/src/main/java/io/swagger/annotations/Api.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParam.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParams.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiModel.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiModelProperty.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiOperation.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiResponse.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiResponses.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/Authorization.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/AuthorizationScope.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/Contact.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/Extension.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ExtensionProperty.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ExternalDocs.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/Info.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/License.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/ResponseHeader.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/SwaggerDefinition.java, modules/swagger-annotations/src/main/java/io/swagger/annotations/Tag.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/ReaderListener.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/json/JacksonJsonProvider.java
This fixes #1366 by replacing all JavaDoc uses of `<p/>` with `<p>`
[Here's some Oracle documentation indicating the correct usage of `<p>` instead of `<p/>`](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#format)
After applying this fix, builds using Java 8 can complete successfully
=> Switch to Java 8 compatible HTML markup in JavaDoc 

modules/swagger-models/src/main/java/io/swagger/models/HttpMethod.java, modules/swagger-models/src/main/java/io/swagger/models/Path.java
No `HEAD` in enum `HttpMethod`, no `head` in `Path.getOperationMap()`.
It seems wrong, so I created this PR.
Pls check and merge.
Thanks!
=> head operation in `Path`

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/util/JsonDeserializationTest.java, modules/swagger-core/src/test/resources/specFiles/propertyWithVendorExtensions.json
Regarding the discussion in swagger-api/swagger-spec#241 this adds deserialization for vendor extensions to ArrayProperty.
ObjectPropery and MapProperty are already taken care of in swagger-api/swagger-core/pull/1414
=> Add vendor extensions to ArrayProperty. [241]

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/BeanValidatorTest.java, modules/swagger-core/src/test/java/io/swagger/models/BeanValidationsModel.java
I don't know if it is valid thing to do but (ie. `ECMA262` regex is little bit different than Java), but until proper conversion will be done, there is no way how to specify regex for swagger from annotations other than simply reuse `@Pattern` annotation.
=> Add support for javax.validation.Pattern

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleScannerTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/SimpleSelfReferencingSubResource.java
Hi Ron,
here is a new PR based on our discussion from last week.
The sub resource paths are shown/included along the paths until we see a recursive reference.
thanks.
regards, aki
=>  #1424 avoid an endless scan by not scanning resources over a recursive reference

modules/swagger-models/src/main/java/io/swagger/models/RefModel.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/RefParameter.java, modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java, modules/swagger-models/src/main/java/io/swagger/models/refs/GenericRef.java, modules/swagger-models/src/main/java/io/swagger/models/refs/RefConstants.java, modules/swagger-models/src/main/java/io/swagger/models/refs/RefType.java, modules/swagger-models/src/test/java/io/swagger/GenericRefTest.java
Assuming the discussion in #1388 doesn't result in there being a valid reason not to allow PATH and RESPONSE as internal refs, this is a solution which simply allows those.
This commit does those things:
* move the internal prefixes into the RefType enum (→ RefConstants class is not needed anymore)
* add prefixes for RESPONSE and PATH
* get rid of the exception when trying to use an internal reference of type RESPONSE or PATH
* add test cases in GenericRefTest for PATH and RESPONSE.
=> Fix Issue #1388: allow path and response refs, too.

pom.xml
Hi Ron,
it took a while because it confused me that the maven build of swagger was not automatically adding the exported version as in the other projects that I had. Then I noticed that swagger was using maven-bundle-plugin 2.3.4. whereas the other projects that I had were using a newer version either 2.3.7, 2.4.0, or 2.5.4 and they are all automatically generating the exported version number. After switching swagger to use 2.3.7, the version numbers are now correctly included. So, I needed just a single line change ;-)
regards, aki
=> update felix-plugin to generate the exported version numbers correctly

modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/ReflectionUtilsTest.java, modules/swagger-core/src/test/java/io/swagger/reflection/IParent.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/AnnotatedInterface.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/AnnotatedInterfaceImpl.java
Fixes #1427: Processing annotations on interfaces has been fixed
=> Fixes #1427: Processing annotations on interfaces has been fixed

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ObjectProperty.java
When deserializing a Swagger definition containing an inline schema, the said schema's property is not set in the object `ObjectProperty`. 
Extract from my definition: 
```json
"paths": {
"/path1": {
"get": {
"summary": "Swagger.paths.*.*.summary",
"responses": {
"default": {
"description": "Swagger.paths.*.*.responses.*.description",
"schema": {
"type": "object",
"description": "Swagger.paths.*.*.responses.*.schema.description",
"properties": {
"property1": {
"type": "string",
"description": "Swagger.Paths.*.*.responses.*.schema.properties.*.description"
}
}
}
}
}
}
}
}
```
Which means the following: 
```java
Swagger swagger = Json.mapper().readValue(myFile, Swagger.class);
System.out.println(swagger.getPath("/path1").getGet().getResponses().get("default").getSchema().getDescription()); …
```
=> Description lost during object property deserialization

modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java
Fixes #1475: java.time.LocalDate and java.time.LocalDateTime have been added to PrimitiveType for java8
=> Fixes #1475: java.time.LocalDate and java.time.LocalDateTime have been added to PrimitiveType for java8

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java
Fixes #1440: Nickname, if specified, is now used as operationId
=> Fixes Issue #1440: Use nickname, if specified, as operationId

modules/swagger-models/src/main/java/io/swagger/models/auth/AbstractSecuritySchemeDefinition.java, modules/swagger-models/src/main/java/io/swagger/models/auth/SecuritySchemeDefinition.java
The field description of [security definitions](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-15) is missing from the Java POJO, thus lost during deserialization. 
Tested with Swagger containing: 
```json
"securityDefinitions": {
"securityDefinition1": {
"type": "basic",
"description": "Swagger.securityDefinitions.*.description"
}
}
```
And main method: 
```java
Swagger swagger = Json.mapper().readValue(file.toFile(), Swagger.class);
System.out.println(swagger.getSecurityDefinitions().get("securityDefinition1").getDescription());
```
Output: `Swagger.securityDefinitions.*.description`
=> Add description field in security definitions

modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java
genericRef can be null in RefProperty so add checking for null to avoid NPE
Ref: https://github.com/swagger-api/swagger-codegen/issues/1267
=> Fix NPE with genericRef in RefProperty

modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithImplicitFileParam.java
from https://github.com/swagger-api/swagger-core/commit/62c100f33a54d7688e859cd011abb89a907e02ef, it appears the example is setting the type parameter, which is obviously wrong.
=> fixes #1526

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiResponses.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/CustomException.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithCustomException.java
A common pattern in JAX-RS applications is to have resources throw
custom exceptions, and configure an ExceptionMapper to map them to a
specific HTTP status code.
This pattern does not mesh well with how swagger collects the APIs
info: swagger expects the developer to declare for every method the
list of possible responses, regardless of the exceptions it declares to
throw.
```java
@PUT
@ApiOperation("desc")
@ApiResponses({
@ApiResponse(code = 204, message = "Everything is awesome")
@ApiResponse(code = 500, message = "Internal error")
@ApiResponse(code = 502, message = "Upstream error")
})
@Path("/op")
void operation(Params params) throws UpstreamServerError, InternalServerError;
```
This pull request proposes to also check the exceptions declared in the
throws clause of a method for …
=> Include responses from a method's declared exceptions

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/properties/PropertySerializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ObjectProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/main/java/io/swagger/models/properties/StringProperty.java
Handle property _required_ of `ObjectProperty` during serialization and deserialization. 
Running the code below: 
```java
ModelImpl model = new ModelImpl()
.property("prop",
new ObjectProperty()
.name("Prop")
.required(true)
.property("stringProperty", new StringProperty()
.required(true)
.title("stringProperty")));
System.out.println(Json.pretty().writeValueAsString(model););
```
Was outputting:
```json
{
"required" : [ "prop" ],
"properties" : {
"prop" : {
"type" : "object",
"properties" : {
"stringProperty" : {
"type" : "string",
"title" : "stringProperty"
}
}
}
}
}
```
The _required_ field of the `ObjectProperty` was ignored.
When deserializing the following JSON: 
```json
{
"required" : [ "prop" ],
"properties" : {
"prop" : {
"type" : "object",
"properties" : {
"stringProperty" : { …
```
=> Fix serialization/deserialization of 'required' property on ObjectProperty

modules/swagger-models/src/main/java/io/swagger/models/Swagger.java
When deserializing a Swagger with API level vendor extensions, I get an NPE on `.swagger.vendorExtensions`.
The field being null by default, there should be an NPE check when trying to add an element to it.
Deserialize the following Swagger.
```java
Yaml.mapper().readValue(pathToTheSwaggerFile, Swagger.class);
```
```yaml
---
swagger: "2.0"
info:
version: "1.0"
title: "Protect-Policy-Summary"
contact: {}
host: "localhost:8501"
basePath: "/api"
tags:
- name: "{policyNumber}"
schemes:
- "http"
paths:
/{policyNumber}:
get:
tags:
- "{policyNumber}"
summary: "Retrieve Protect Policy-level data"
description: "Retrieve Protect Policy-level data"
operationId: "getPolicyNumber"
consumes: []
produces:
- "application/json"
parameters:
- name: "policyNumber"
in: "path"
required: true
type: "string"
- …
```
=> Fix deserialization of Swagger with API-level vendor extensions

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/InheritedBeanTest.java
When a class is a referred to in a @ApiModel(subClasses) the
properties from the base class are supposed to be removed from
the subclass. There was code to do this, but the properties of
the base class had not been set before an attempt was made to
loop through them.
Added test to verify behavior
=> Properly filter subclass properties

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/WebXMLReader.java
This commit adds two new configurations from the `web.xml`, and backwards-compatible support for the previous `basePath` setting.
When configuring the `DefaultJaxrsConfig`, you can configure each section as such:
```xml
<servlet>
<servlet-name>DefaultJaxrsConfig</servlet-name>
<servlet-class>io.swagger.jaxrs.config.DefaultJaxrsConfig</servlet-class>
<init-param>
<param-name>api.version</param-name>
<param-value>1.0.0</param-value>
</init-param>
<init-param>
<param-name>swagger.api.basepath</param-name>
<param-value>/v2</param-value>
</init-param>
<init-param>
<param-name>swagger.api.host</param-name>
<param-value>foo.bar.com:8909</param-value>
</init-param>
<init-param>
<param-name>swagger.api.schemes</param-name>
<param-value>https,http</param-value>
</init-param> …
```
=> added host, schemes, proper handling of basePath

modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithValidation.java
As discussed with @fehguy, fixes #1438 adding support for JSR-303 annotations @Min, @Max and @NotNull (@Size was already processed) for operation parameters.
Behvaiour changes include: 
* If @NotNull, parameter 'required' will always be true (e.g. also if @ApiParam (required = false))
* If @Min(x) or @Max(x), parameter 'minimum' or 'maximum' will be set to x only if @ApiParam (allowableValues) is not specified.
=> refs #1438 adds jsr-303 to param

modules/swagger-core/src/main/java/io/swagger/core/filter/AbstractSpecFilter.java, modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/RemoveUnreferencedDefinitionsFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/paramAndResponseRef.json, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java
@fehguy 
solution for #1557, allowing to filter out unreferenced definitions from returned Swagger, if specified in filter by extending `AbstractSpecFilter` and overriding `isRemovingUnreferencedDefinitions()`:
```java
public class RemoveUnreferencedDefinitionsFilter extends AbstractSpecFilter {
public boolean isRemovingUnreferencedDefinitions() {
return true;
}
}
```
Checks for the following references and compares with definitions:
swagger.parameters.parameter(BodyParam).schema
swagger.responses.Response.schema
swagger.paths.Path.parameters.parameter(BodyParam).schema
swagger.paths.Path.operations.Operation.responses.Response.schema
swagger.paths.Path.operations.Operation.parameters.parameter(BodyParam).schema
Method `isRemovingUnreferencedDefinitions` has not been added to interface …
=> #1557 filter out unreferenced definitions if specified in filter

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java, modules/swagger-jaxrs/src/test/java/com/subresourcesTest/ChildResource.java, modules/swagger-jaxrs/src/test/java/com/subresourcesTest/RootResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/BeanConfigTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/HiddenParametersScannerTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReferenceTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/RegexPathParamTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/SubResourceReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithSubResources.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/SubResource.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/ScannerTest.java
@fehguy Refs #1106, #1629, #1617, #1614
As discussed, changes JAX-RS root and subresources identification, scanning and reading to be compliant with JAX-RS specs: Root resources are identified by @Path annotation at class level, and sub resources are identified by @Path annotation at method level, along with no @HttpMethod annotation.
It integrates changes from #1617, changing BeanConfig scanning to only consider @Path annotations, and #1629, used as base for further implementation.
Classes not annotated with @Path are only read in case config.scanAllResources is true, maintaining anyway @Api.hidden processing (@Api.hidden classes are never processed).
Tests have been adapted by setting always scanAllResources = true to be able to handle current test root resources classes which are not …
=> Refs #1106, #1629, #1617, #1614 - JAX-RS Root and Subresources identification, scanning and reading

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/XMLInfoTest.java
Adding functionality, if class is tagged XmlAccessType.NONE and the
property is not tagged XmlElement, the property is ignored in the
output.
=> Ignore property if XmlAccessType.NONE and no XmlElement

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java
When setting dataType on ApiModelProperty annotation, where the type is referenced from an ApiImplicitParam annotation - I get the below exception, running from Play Framework 2.4.6.
This issue may be relevant to other frameworks. This is due to the framework's customized class loading mechanism. In play - the project sources are loaded in a child class loader of the loaded dependencies, this cater for hot swapping during development. As a side effect, a class imported as a dependency can't load a local project class from it's current class loader or one of it's parent class loaders.
Sorry for the lack of UT coverage, it was difficult for me to simulate such a scenario.
```
Caused by: java.lang.IllegalArgumentException: Unrecognized Type: [null]
at …
```
=> dataType class loading issue in managed containers such as play framework

modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/Property.java
Removal of `Property#setExample(String)` can cause linkage errors at runtime, if there are conflicting versions of swagger-models. For example, springfox-swagger2 uses swagger-core:1.5.6, which pulls in swagger-models:1.5.6. If swagger-codegen is also in the classpath, `Property#setExample(String)` from the swagger-models:1.5.6 clashes with `Property#setExample(Object)`; overriding the transitive dependency is not an option due to the incompatible signature-change. This change adds the method back to the `Property` class but marks it as deprecated, thereby preserving backwards-compatibility.
=> issue #1667

modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ServletReaderExtension.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/ReaderTest.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/extensions/PathGetterTest.java
Fix #1512 - doesn't consider anymore nickname for path building in swagger-servlet. 
Note: nickname is still used in swagger-jaxrs, we would possibly have a consistent behaviour and apply the change also in jaxrs
=> Fix #1512 - nickname not to be considered for path

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithCustomHTTPMethodAnnotations.java
Solution to defect: [#1643](https://github.com/swagger-api/swagger-core/issues/1643).
Currently Javax does not support the PATCH annotation so some users have created their own in the form below to avoid them coupling their code to Swaggers `io.swagger.jaxrs.PATCH`:
```
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@HttpMethod("PATCH")
public @interface PATCH{ 
}
```
Which is picked up by Jersey but not by Swagger. This change makes swagger check through all resource method annotations to find the HttpMethod like above.
=> Allow user created @PATCH, @GET ...etc annotations

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerConfigLocator.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerContextService.java, modules/swagger-jaxrs/src/test/java/io/swagger/SwaggerContextServiceTest.java
@webron 
Fix for ignored swagger config via context attribute as reported by testuser1234 on IRC.
Before the fix, swagger configuration via  `context.setAttribute("swagger", swagger);` in client Bootstrap servlet (or equivalent)  would not be picked up by swagger
A workaround for unpatched code is configuring via new mechanism like:
`new SwaggerContextService().withServletConfig(config).updateSwagger(swagger);`
=> fixes ignored swagger config via context attribute

modules/swagger-models/src/main/java/io/swagger/models/properties/Property.java
Refs #1107, #1318, #1118, https://github.com/kongchen/swagger-maven-plugin/issues/233
initially triggered by #1107 analysis, solves possibly regression related to #1640, causing property field "example" not to be serialized to json.
This fix doesn't solve however neither #1107 (swagger-ui related, but probably solved by updating core/models) nor #1118 and it doesn't address similar discussion in https://github.com/kongchen/swagger-maven-plugin/issues/233.
Either part of this PR, or of further work on #1118, the following steps could be taken to cover the whole "area".
1 - Resolving from ApiModelProperty annotation.
similarly to discussion in https://github.com/kongchen/swagger-maven-plugin/issues/233, code could be enhanced to parse example value according to format and property type.
2 - …
=> Refs #1107, #1318, #1118 - property example serialization

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/deserialization/JsonDeserializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ArrayProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/MapProperty.java
During deserialization of non-primitive properties, the attribute `title` was lost. Now it is retrieved in all cases.
See `JsonDeserializationTest#testObjectProperty` for a live example. 
- remove unused `xml` element in `PropertyDeserializer#propertyFromNode`
- invert conditions in assertEquals in `JsonDeserializationTest#testObjectProperty`. The `expected` & `actual` values were in the wrong order resulting in confusing Junit traces (`expected: <0> but was: <3>` instead of `expected: <3> but was: <0>`).
=> Add 'title' attribute during deserialization of non-primitive properties

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiResponse.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithCustomExceptionAndClassLevelApiResource.java
@fehguy 
Close #1382 - @ApiResponse at class level get parsed and merged in operation responses if a response with same code is not defined at method level or in thrown Exception
wiki update in https://github.com/frantuma/swagger-core/wiki/Annotations-1.5.X/10a2248ce5072c74c52b8ce0dc7a0fdc2522095e
=> Close #1382 - @ApiResponse at class level

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithClassLevelApiResourceNoMethodLevelApiResources.java
Fix #1717 - fix NPE with @ApiResponse at class level and no response in operation or @ApiOperation not defined for method
=> Fix #1717 - NPE with @ApiResponse at class level and no operation response

modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java
Didn’t write a test because swagger-core is compiled for Java 6.
=> Consider java.time.ZonedDateTime a Swagger DateTime primitive

modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java
Add support for java8 java.time.instant
See https://github.com/swagger-api/swagger-core/issues/1445
=> Update PrimitiveType.java to add support for java8 java.time.instant

modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithAnnotationsOnlyInInterface.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithAnnotationsOnlyInInterfaceImpl.java
This fixes issue 1746.
I changed two lines in Reader.java to support these annotations in interfaces/superclasses and provided two testcases for this.
Also credit to [mohitmutha](https://github.com/swagger-api/swagger-core/issues/1506) for finding a solution to a similar problem and @captdestrukto to provide a [pull request](https://github.com/swagger-api/swagger-core/pull/1735) for that one
Please note that my pull request also incorporates the changes proposed by captdestrukto; it is a cumulative pull request :)
=> Fixed issue 1746 - Api and ApiImplicitParam annotations not read when they are in a parent of the resource class

modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java
This is a fix for issue #1506.
Reader got parameter annotations from a child method, ignoring any
on a parent class or interface. This fix will look for annotation
on the parent class or interface, if it exists. Credit mohitmutha
with the fix. I just implemented it and created the pull request.
=> Look for parameter annotations on parent classes/interfaces.

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/DefaultJaxrsScanner.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/DefaultReaderConfig.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/ReaderConfig.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/ReaderConfigUtils.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/ReflectiveJaxrsScanner.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerContextService.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/WebXMLReader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ext/SwaggerExtensions.java, modules/swagger-jaxrs/src/test/java/io/swagger/ApiListingResourceTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReferenceTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/SwaggerConfigLocatorTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/SwaggerContextServiceTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/ApiListingResourceIT.java, modules/swagger-jaxrs/src/test/java/io/swagger/models/TestEnum.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/AnnotatedInterfaceImpl.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/BookResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/NoPathSubResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithCustomHTTPMethodAnnotations.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithSubResources.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/SubResourceHead.java
I did some code cleanup in the jaxrs module.
=> code cleanup in the jaxrs module

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/NotValidRootResource.java
in v1.5.8 JAX-RS scan behaviour was updated to mandate @Path annotation at class level to have the class scanned, also without any @Api annotation; This patch applies instead behaviour as in Option 4 table of #1636, therefore "in standard mode" (no scanAllResources, no hidden) both annotation need to be present for the class to be scanned.
=> Refs #1636, applies Option 4 scanning model

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/DefaultJaxrsConfig.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerContextService.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/BaseApiListingResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/SwaggerContextServiceTest.java
Includes #1656 - "Allow to use of multiple Swagger configurations per single ServletConfig using base path as descriminator", adds basePath support in DefaultJaxrsConfig.
Please see #1656 for details.
=> Includes #1656 - Allow to use of multiple Swagger configurations per single ServletConfig using base path as descriminator

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/SwaggerContextService.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/BaseApiListingResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/SwaggerContextServiceTest.java
Hey guys,
Please take a look on this enhancement which allows to use multiple Swagger configurations per single servlet (more precisely, ServletConfig). Essentially, this is more generic approach than the one taken by https://github.com/swagger-api/swagger-core/issues/1482 and is using the base path as a unique context discriminator. The original discussion has been started here https://groups.google.com/forum/#!topic/swagger-swaggersocket/bf7uVBWYRTw and the solution suggested by @frantuma has been implemented.
There are two configuration parameters available:
- Servlet init parameter '**swagger.use.path.based.config**' = true | false
- **usePathBasedConfig** property of BeanConfig
When those properties are set, the **SwaggerContextService** is going to use base path to uniquely identify …
=> Allow to use of multiple Swagger configurations per single ServletConfig using base path as descriminator

modules/swagger-jersey-jaxrs/pom.xml
There was unnecessary dependencies on both `jersey-server` and `jersey-client` in `swagger-jersey-jaxrs`.
=> Remove unused deps in swagger-jersey-jaxrs

modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java
fix #1831 - fix ConcurrentModificationException in SpecFilter, by getting a copy of properties Map while cloning.
=> fix #1831 - fix ConcurrentModificationException in SpecFilter

modules/swagger-core/src/test/java/io/swagger/parameter/ParameterSerializationTest.java, modules/swagger-core/src/test/java/io/swagger/properties/PropertySerializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/SerializableParameter.java
Fixes #1765, implements additional "enumValue" of type Object to correctly handle numeric values
This replaces  PR #1807 maintaining backward compatibility (as much as possible: enum for numeric parameters are serialized in Json/Yaml as numbers and not any more strings). It implements a solution similar to "defaultValue" as suggested by @tomtit. 
@tomit can you please have a look and let me know if you think this is ok?
update: discussed with tomit and updated according to suggestions (fall back to string at item level)
=> refs #1765 - numeric enums in parameter

modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/listing/ApiListingResourceJSON.java
As discussed in #1714, remove @Path and deprecates ApiListingResourceJSON
=> Fix #1714 - removed @Path from ApiListingResourceJson and deprecated

modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/paramAndResponseRefArray.json
Should fix #1757.  I was unsure of how to get the ref (or refs) from ComposedModel objects, so I left them out.
=> Ref #1757: Retain refs from Array/Map Property types when using "removingUnreferencedDefinitions"

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ext/AbstractSwaggerExtension.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ext/SwaggerExtension.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleScannerWithDecoratorExtensionTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/SimpleResourceWithVendorAnnotation.java
It should be possible to enrich swagger model by vendor based extensions stored on operation level. To do that we need to add extension point when operation is processed and method context exists. This allow to process e.g. some vendor annotation which are stored on method level and could be used by documentation.
=> Method level reader extensions

modules/swagger-core/src/test/resources/Animal.json, modules/swagger-core/src/test/resources/Cat.json, modules/swagger-core/src/test/resources/Pet.json, modules/swagger-models/src/main/java/io/swagger/models/properties/BooleanProperty.java
Code for parseBoolean:
```
public static boolean parseBoolean(String s) {
return ((s != null) && s.equalsIgnoreCase("true"));
}
```
So when the BooleanProperty has no default value (e.g. s == null), we are setting the default value as false.
One of the problems caused by this issue:
https://github.com/kongchen/swagger-maven-plugin/issues/284
=> Use null Instead of false When No Default Value is Provided

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java
Fixes failure when reading an `ApiKeyAuthDefinition` inside a `SwaggerDefinition`
=> Use In.forValue instead of In.valueOf in SwaggerDefinition reader

modules/swagger-core/src/test/java/io/swagger/ParameterProcessorTest.java
Fixes #1917 
To use the `ApiImplicitParam` annotation for an array type, use the `allowMultiple=true` value in the annotation, as shown in this test
=> added test

modules/swagger-models/src/main/java/io/swagger/models/Swagger.java
`Swagger.gePaths()` should return original map without sort by key.
See comment https://github.com/swagger-api/swagger-core/pull/1934#discussion_r79721354
=> Swagger.gePaths() return original map

modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/Resource1970.java
For issue #1970, there was no way to override the dataType for implicit parameters to `BigDecimal`, otherwise `number` in the system.
With this patch, you can use the following annotation:
```
@ApiImplicitParams({@ApiImplicitParam(name = "param1", dataType = "number", paramType = "path", required = true)})
```
And the parameter type will be correctly reported as `number`
=> Added conversion from type `number` to BigDecimal

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiParam.java, modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java
=> added format override

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/util/JsonDeserializationTest.java, modules/swagger-core/src/test/resources/specFiles/propertiesWithConstraints.json, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java
Small fix for #1201 (missing deserialisation of ArrayProperty constraints (`minItems`, `maxItems` and `uniqueItems`).
=> Fixing 1201 - array property constraint deserialisation

modules/swagger-jaxrs/.gitignore, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java, modules/swagger-jaxrs/src/test/java/com/splitresourcesTest/SplitResource.java, modules/swagger-jaxrs/src/test/java/com/splitresourcesTestImpl/SplitResourceImpl.java, modules/swagger-jaxrs/src/test/java/io/swagger/BeanConfigTest.java
Modification to allow inclusion of a concrete resource classes annotated with @Api combined with superinterfaces of the concreate class annotated with @Path.
Detailed in : #1800
=> Allow scanning of split resources (#1800)

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/DefaultParameterExtension.java
At the moment if you use frameworks like FreeBuilder (https://github.com/google/FreeBuilder) to create POJOs (with builders), you end up with interfaces or abstract classes that only have getters (with builders and concrete classes being automatically generated at compilation time).
Previously that meant that those objects would be ignored by Swagger if used as @BeanParam on jersey resources; this change allows type params and annotations (like @QueryParam) to be picked up from getters.
=> Infer bean param type also from getters

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/BaseApiListingResource.java
This allows to customize lookup logic above of provided Swagger api. This solves #1887.
=> Allow overriding of BaseApiListingResource.process method.

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParams.java
When using ApiImplicitParams on a custom annotation you can avoid duplicating repeated parameter definitions.
``` java
@Api(value = "lots of API endpoints here...")
public class LotsOfMethodsController{
@ApiOperation(value = "Method1")
@MySwaggerImplicitSecurityHeader
public void ApiMethod1(){}
@ApiOperation(value = "Method2")
@MySwaggerImplicitSecurityHeader
public void ApiMethod2(){}
//...with more of these ApiMethods down the line
@Retention(value = RetentionPolicy.RUNTIME)
@ApiImplicitParams({@ApiImplicitParam(name = "x-my-custom-auth-header-that-keeps-repeating", required = true, dataType = "string", paramType = "header",defaultValue = "SOME_TEST_TOKEN_VALUE")})
public @interface MySwaggerImplicitSecurityHeader { }
}
```
=> Make ApiImplicitParams available for annotation types

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParams.java, modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/ReflectionUtilsTest.java, modules/swagger-core/src/test/java/io/swagger/reflection/Child.java, modules/swagger-core/src/test/java/io/swagger/reflection/IParent.java, modules/swagger-core/src/test/java/io/swagger/reflection/IndirectAnnotation.java, modules/swagger-core/src/test/java/io/swagger/reflection/Parent.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/IndirectAnnotation.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/IndirectImplicitParams.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/IndirectImplicitParamsImpl.java
This builds upon #1925, and allows for `@ApiImplicitParams` at class level, as well as meta-annotations which use `@ApiImplicitParams` at class level. For example (adapted from #1867) :
```
@Retention(value = RetentionPolicy.RUNTIME)
@ApiImplicitParams({@ApiImplicitParam(name = "x-my-custom-auth-header-that-keeps-repeating", required = true, dataType = "string", paramType = "header",defaultValue = "SOME_TEST_TOKEN_VALUE")})
public @interface MySwaggerImplicitSecurityHeader { }
@Api(value = "lots of API endpoints here...")
@MySwaggerImplicitSecurityHeader
public class LotsOfMethodsController {
@ApiOperation(value = "Method1")
public void ApiMethod1(){}
@ApiOperation(value = "Method2")
public void ApiMethod2(){}
//...with more of these ApiMethods down the line
} 
```
=> Add support for @ApiImplicitParams at class level

modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java, modules/swagger-core/src/test/java/io/swagger/ParameterProcessorTest.java
According to #1873  the path parameters are ignoring the data type input, except for file data type, so in order to fix this issue the path parameter must be set with the right property according primitive data type.
note: I must say that in this change, issue is fixed only for long primitive, since at this moment i'm ignoring the input/output matching for data types.
=> #1873 fixed output convertion for long data type.

modules/swagger-core/src/test/java/io/swagger/util/JsonSerializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/AbstractModel.java, modules/swagger-models/src/main/java/io/swagger/models/ExternalDocs.java, modules/swagger-models/src/main/java/io/swagger/models/Info.java, modules/swagger-models/src/main/java/io/swagger/models/License.java, modules/swagger-models/src/main/java/io/swagger/models/Operation.java, modules/swagger-models/src/main/java/io/swagger/models/Path.java, modules/swagger-models/src/main/java/io/swagger/models/Response.java, modules/swagger-models/src/main/java/io/swagger/models/SecurityRequirement.java, modules/swagger-models/src/main/java/io/swagger/models/Swagger.java, modules/swagger-models/src/main/java/io/swagger/models/Tag.java, modules/swagger-models/src/main/java/io/swagger/models/auth/AbstractSecuritySchemeDefinition.java, modules/swagger-models/src/main/java/io/swagger/models/auth/In.java, modules/swagger-models/src/main/java/io/swagger/models/auth/OAuth2Definition.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractParameter.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/BodyParameter.java, modules/swagger-models/src/main/java/io/swagger/models/properties/AbstractProperty.java
Please consider using LinkedHashMap as a default Map implementation #2021
=> Use LinkedHashMap as default map implementation #2021

modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/ReflectionUtilsTest.java, modules/swagger-core/src/test/java/io/swagger/reflection/Child.java, modules/swagger-core/src/test/java/io/swagger/reflection/IGrandparent.java, modules/swagger-core/src/test/java/io/swagger/reflection/IParent.java
Issue 1894 identified an issue where Reflection.isOverriddenMethod could not tell if the method was over ridden in another interface.
This now looks for interfaces & any superclass and then loops through them all, performing the same logic as before
=> #1894 Fixed Reflection.isOverriddenMethod to detect interface inheritance

modules/swagger-core/pom.xml, modules/swagger-core/src/test/java/io/swagger/jackson/SwaggerTestBase.java, modules/swagger-jaxrs/pom.xml
swagger-jaxrs has a number of jackson dependencies in its pom.xml but it appears it only really needs jackson-databind.
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-3720 is open against jackson-dataformat-xml and this fix removes that dependency from swagger-jaxrs
=> remove unused jackson dependencies from swagger-jaxrs

modules/swagger-core/src/main/java/io/swagger/converter/ModelConverterContextImpl.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/InheritedBeanTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/ChildTypeTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/models/BaseBean.java, modules/swagger-jaxrs/src/test/java/io/swagger/models/Sub1Bean.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithChildType.java
Resolves [issue 1896](https://github.com/swagger-api/swagger-core/issues/1896). 
**Issue Summary**
(Please refer to the issue for more details and examples)
When the io.swagger.jackson.ModelResolver's resolve method is called with a parent type, the ModelResolver will create a parent model, as well as a child composition model that references that parent model and does not contain the parent properties. However, when called with a child type, the ModelResolver will create a single model containing both the parent and child properties. 
...details from issue omitted here...
I have updated ModelResolver so that, when presented with the child class as its starting point, the resolve method will define the same set of models in the ModelConverterContext that it would define when presented …
=> #1896 Fixed io.swagger.jackson.ModelResolver - Composition model when resolving child type

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/DefaultJaxrsScanner.java
Handling pretty print is not necessary in DefaultJaxrsScanner because it's handled by AbstractScanner.
This own handling causes io.swagger.jaxrs.listing.ApiListingResource to read the wrong pretty print state.
With the proposed fix it will work correct.
=> Pretty print is handled by AbstractScanner

modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java, modules/swagger-core/src/test/java/io/swagger/MapPropertyDeserializerTest.java
The example in the response should be kept.
```
swagger: '2.0'
info:
version: 1.0.0
title: Inline schema example
paths:
/user:
get:
produces:
- application/json
responses:
200:
description: OK
schema:
type: object
properties:
id:
type: integer
format: int32
name:
type: string
required: [id, name]
example:
id: 42
name: Arthur Dent
```
=> Include example from inlined response schemas.

pom.xml
Just a bugfix release. Changelog found [here](https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION#L69-L84).
=> Update jackson from 2.8.4 to 2.8.5

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiImplicitParam.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ClassWithExamplePostClass.java
https://github.com/swagger-api/swagger-core/issues/1564
I'm sure there is a bit more needed here but it would be nice to support classes directly like in other swagger annotations. In my dev team, the most common error with swagger is to not properly fully reference the class names in @ApiImplicitParam dataType.
=> support @ApiImplicitParam dataTypeClass

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/AcceptHeaderApiListingResource.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/BaseApiListingResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/ApiListingResourceTest.java
As discussed in #2105 
I decided to let the `JsonProcessingException` just go all the way up, as this is closest to what would happen if a JsonProcessingException was thrown when Jackson tries to serialize the object.
=> use custom object mapper to serialize json in order to avoid null values

modules/swagger-models/src/main/java/io/swagger/models/refs/GenericRef.java, modules/swagger-models/src/test/java/io/swagger/GenericRefTest.java
Just because a ref starts with "http" does not mean it is a URL.
For example, a user may have models with names like "httpOptions",
"httpHeaders", "httpAuthentication", etc.  Internal refs to such
models were incorrectly being treated as if they were external
URL references.
=> fix GenericRef treating refs starting with http as URLs

modules/swagger-core/src/test/java/io/swagger/util/JsonDeserializationTest.java, modules/swagger-core/src/test/resources/specFiles/propertiesWithConstraints.json, modules/swagger-models/src/main/java/io/swagger/models/properties/ByteArrayProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java
A base64 encoded string (type: "string", format: "byte") is correctly identified as byte array but lacks support for min- and max length. This pull request adds this support.
Additionally the base64 string should follow a regex pattern that roughly ensures a real base64 encoded string. "ABC" is not a base64 encoded string and therefore should fail the schema validation.
=> #2141 add support for min- and maxLength for base64 encoded strings

pom.xml
Update to logback v1.2.3 addresses threat CVE-2017-5929.   Ref issue #2182 
Unit tests not run/created as I am not a developer or have the tools.
=> Update logback version to 1.2.3

modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ServletReaderExtension.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/ReaderTest.java, modules/swagger-servlet/src/test/java/io/swagger/servlet/extensions/PathGetterTest.java
problem : Earlier method name was postfixed in the api path, if Nick name is being provided then the nickname should have higher priority over method name
Proposed Fix : added StringBlank check on field operationPath and setting operationPath in the api path if operationPath is not blank, by doing so i am setting the priority of nick name over method name.
=> Now Using operationPath to override the nature of actual path

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/ModelResolverTest.java, modules/swagger-core/src/test/java/io/swagger/jackson/package-info.java
This PR addresses Issue [2150](https://github.com/swagger-api/swagger-core/issues/2150). When resolving a `JavaType` to a Swagger `Model`, if the type is annotated with `XmlRootElement` and no namespace is specified, the resolver will look in `package-info` for an package-level annotation.
=> Get namespace from package-info #2150

modules/swagger-core/src/main/java/io/swagger/util/Json.java, pom.xml
Where I work we're strict about maven version conflicts. Would there be any problem with bumping some of the swagger dependencies.
Full disclosure: These versions have been chosen to line up with dropwizard 1.1.0. The reflections one is the main one to update as the current version pulls in a defunct google annotations jar, the others are just nice-to-have.
=> Bump versions

modules/swagger-core/src/main/java/io/swagger/jackson/SwaggerAnnotationIntrospector.java
The Bugfix was added
The solution was implemented in the SwaggerAnnotationIntrospector adding a new validation in the hasIgnoreMarker method, when there's a Hidden field and the constructor is treated with a JsonCreated it mark the Constructor as ignored. So, when it try to remove the property it doesn't have any trouble to do it.
The Tests weren't added because we don't want to add the Lombok annotations to our projects. 
@fehguy
=> 2061-Validation-added

README.md
The maven install will fetch the required jackson jars (currently 2.8.x).
=> Remove jackson pre-req from README.md

modules/swagger-models/src/main/java/io/swagger/oas/models/headers/Header.java, modules/swagger-models/src/main/java/io/swagger/oas/models/parameters/Parameter.java
Examples in header should be a map instead of a List, header should follow the structure of a parameter as says in:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#header-object
=> fix examples map on header

modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/OperationParser.java
PR for #2442 :
- Copy missing `@Schema` annotation fields over into `Schema` model object.
=> Processing missing @Schema elements when creating Schema objects from Schema annotations

modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/OpenAPIDefinition.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/headers/Header.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/servers/Servers.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/tags/Tag.java, modules/swagger-annotations/src/main/java/io/swagger/oas/annotations/tags/Tags.java
Issue #2317 - New annotations Servers, Tag, Tags, OpenAPIDefinition + minor fixes
Note: once these annotation are pulled in, we'll make another PR for Reader processing these annotations (under swagger-jaxrs2 project)
=> Issue #2317 - New annotations Servers, Tag, Tags, OpenAPIDefinition + minor fixes

modules/swagger-jaxrs2/src/main/java/io/swagger/jaxrs2/DefaultParameterExtension.java
As described in #2466, this pull request will fix the wrong schema generation if BeanParams with generic attributes are used. The bug was originally introduced by commit 26f9572.
This is the pull request for the 2.0 branch.
=> #2466 retain generic types for attributes of BeanParam

modules/swagger-jaxrs/pom.xml, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/ApiListingResourceIT.java
Also makes the tests get skipped insted of failing when run from outside of maven.
=> Use dynamic port number for integration test

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiModelProperty.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/ModelPropertyExtensionTest.java
Hi,
OpenAPI Spec allows vendor extensions on API model property level. (see https://github.com/OAI/OpenAPI-Specification/issues/241)
I added these to the `@ApiModelProperty` annotation, extended the model resolver and added a test.
I am looking forward to your feedback!
Regards,
Tobi
=> add extensions to api model property

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/DefaultParameterExtension.java, modules/swagger-jaxrs/src/test/java/io/swagger/BeanParamTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/models/ListOfStringsBeanParam.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/BeanParamTest.java, modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/models/ListOfStringsBeanParam.java
ref #2466 - retain generic types for attributes of BeanParam (Updated)
Includes and replaces #2467.
Renames `shouldHandleAdditionalAnnotation` to `isBeanParametersAggregatorAnnotation`
=> ref #2466 - retain generic types for attributes of BeanParam (Updated)

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/DuplicatedOperationMethodNameResource.java
Duplicated Operation Id when it was generated automatically by the method name.
=> ReaderTest Fix (getMethods Order), Reader Fix (Duplicated Operation Id)

pom.xml
there are some bug fixes and better java 9 support
=> Update commons-lang3, commons-io and joda (2.0 branch)

modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithImplicitParams.java
fix #2556 - updated logging for ApiImplicitParam with no datatype defined
=> fix #2556 - updated logging for ApiImplicitParam with no datatype defined

modules/swagger-core/src/test/java/io/swagger/deserialization/JsonDeserializationTest.java, modules/swagger-models/src/main/java/io/swagger/models/properties/ObjectProperty.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/main/java/io/swagger/models/properties/UntypedProperty.java, modules/swagger-models/src/test/java/io/swagger/models/properties/PropertyBuilderTest.java
=> Introduce UntypedProperty

pom.xml
Swagger was using an ancient (mid 2012) version of the maven-bundle-plugin. This uses an even older version of bnd to work out what Swagger's OSGi metadata should be. This old version of bnd uses a naive algorithm for calculating uses constraints which often overspecifies, in this case putting constraints on Jackson and Guava which are not needed. This in turn makes Swagger much harder to deploy in OSGi as Guava's versioning policy is not semantic.
Switching to a more modern maven-bundle plugin fixes this. 
I originally wanted to look at ways to change 2.x to avoid these uses constraints (by changing the API if possible) when I found that the types aren't actually used in the API. It would therefore be great to see this fix back ported to 1.5.x if possible.
Signed-off-by: Tim Ward …
=> [osgi] Update to a more recent maven-bundle-plugin

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/AcceptHeaderApiListingResource.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/BaseApiListingResource.java, modules/swagger-jaxrs/src/test/java/io/swagger/ApiListingResourceTest.java
Revert "use custom object mapper to serialize json in order to avoid
null values"
This reverts commit 3ad759596f321ffb195256e045ec5803c00ee53c.
This fixes issue #2320. The original commit is pointless and dangerous,
as it surprisingly overrides the behavior of SwaggerSerializers.java,
but does essentially the same (but without supporting pretty printing).
=> Revert pointless commit to fix #2320

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
I'm getting the following NPE when trying to use the swagger-maven-plugin to generate my swagger.json file (see exception below).
Problem is related to 'swagger-core' which can thrown a NPE. The inner model seems to be missing - although I cannot explain why. By checking on 'null' value, I could resolve this issue.
Is it possible to investigate this pull request?
```bash
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.5:generate (default) on project api: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.5:generate (default) on project api: null
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) …
```
=> Avoid possible NPE when innerModel is empty

modules/swagger-core/pom.xml, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/PrimitiveType.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java, modules/swagger-jaxrs2/pom.xml, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/util/ReaderUtils.java, modules/swagger-servlet/pom.xml
There are some libs that have dependency on old Guava jars and some APIs have been removed over the years.
The swagger dependency on guava is pretty small, so I'm suggesting it would be nice to remove the dependency altogether.
=> Remove guava dependency from core code (2.0 branch)

modules/swagger-jaxrs2/pom.xml, modules/swagger-jaxrs2/src/main/resources/META-INF/beans.xml, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/cdi2/CDIAutodiscoveryTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/cdi2/DiscoveryTestExtension.java
This tiny beans.xml file allows me to directly use Swagger 2.0's `swagger-jaxrs2` jar in CDI-enabled environments that auto-detect all `@Path` & `@Provider` annotated classes by merely declaring the following dependencies:
```
<dependency>
<groupId>io.swagger.core.v3</groupId>
<artifactId>swagger-jaxrs2</artifactId>
<version>2.0.0-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-annotations</artifactId>
<version>2.9.1</version>
</dependency>
<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>23.0</version>
</dependency>
```
BOOM! Live Swagger-2.0-provided `/openapi*` endpoints that are reflecting my other JAX-RS endpoints! I don't even need Swagger 2.0's convenient config file!
Fixes #2617
=> CDI 2.0 beans.xml for swagger-jaxrs2 integration auto-discovery

modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiOperation.java, modules/swagger-core/src/main/java/io/swagger/converter/ModelConverterContext.java, modules/swagger-core/src/main/java/io/swagger/converter/ModelConverterContextImpl.java, modules/swagger-core/src/main/java/io/swagger/converter/ModelConverters.java, modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java, modules/swagger-jaxrs/src/test/java/io/swagger/JsonViewTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/ApiListingResourceIT.java, modules/swagger-jaxrs/src/test/java/io/swagger/functional/test/resources/CarResource.java
refs #2079 - JsonView support. Includes and replaces #2662 implementing `ignoreJsonView` field in `@ApiOperation` (for backward compatibility) and adding minor fixes and tests.
=>  refs #2079 - JsonView support (includes and replaces #2662)

mvnw.cmd
In Windows batch files, the comment prefix is `REM`, not `#`. This PR fixes an incorrect prefix in `mvnw.cmd`.
=> Fixed incorrect comment prefix (# -> REM) in mvnw.cmd

modules/swagger-models/src/main/java/io/swagger/models/utils/PropertyModelConverter.java
Solution to https://github.com/swagger-api/swagger-parser/issues/672, it was happening when we were trying to convert a spec.
Avoiding NPE changing the if logic.
The Test Case was added in the parser project.
=> refs #672 - NullPointerException when converting an spec

modules/swagger-servlet/src/main/java/io/swagger/servlet/extensions/ServletReaderExtension.java
Aspect frameworks, like AspectJ, may extend or wrap the method making the annotation not to be retrieved using "method.getAnnotations()" . 
Therefore it is necessary to use the provided reflection util to capture these situations all across the reader.
This PR make uniform accross the reader the usage of the reflection util for all "apply*" methods which retrieve Swagger annotations.
=> BUG FIX - Use Reflection extension to capture annotations hidden by an aspect. 

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
Issue is [here](https://github.com/swagger-api/swagger-core/issues/2707)
Enum Names are currently not changed when `@JsonProperty` is used. This PR fixes this bug and allows for `@JsonProperty` to be used for renaming enums.
=> #2707 Overriding Enum Names with @JsonProperty

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/DefaultParameterExtension.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/PetResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/PetResourceSlashesinPath.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/data/PetData.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/Category.java
=> Matrix param support

modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithImplicitParams.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java
=> Fixed override issue on property collectionFormat part of annotation @ApiImplicitParam

modules/swagger-core/src/main/java/io/swagger/core/filter/AbstractSpecFilter.java, modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java
This addresses the use cases where filtering out specific definitions is required.
#2809
=> #2809 Allow filtering of specific definitions in SpecFilter.

modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java, modules/swagger-models/src/test/java/io/swagger/models/parameters/AbstractSerializableParameterTest.java
includes and replaces #2865 (fixes the warning, but doesn't modify the original value)
=>  refs #2783 - avoid NumberFormatException warning with empty String in param example

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/pathItems/OperationsWithLinksTest.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/links/Link.java
**IMPORTANT NOTE**: this PR addresses #2833, by updating `requestBody` member datatype of swagger-models `Link` to be `Object` instead of previous `RequestBody`, as it correctly maps to OpenAPI definition https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#linkObject.
This is a breaking change, but it makes sense as the previous datatype was basically wrong and  meaningless. An alternative would be deprecating requestBody, and introducing a new `requestBodyObject` serialized as JSON `requestBody` via mixin and jackson annotations.
=> refs #2833 - fixes and resolves Links requestBody

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/jackson/mixin/IgnoreOriginalRefMixin.java, modules/swagger-core/src/main/java/io/swagger/jackson/mixin/OriginalRefMixin.java, modules/swagger-core/src/main/java/io/swagger/util/ObjectMapperFactory.java, modules/swagger-core/src/main/java/io/swagger/util/ReferenceSerializationConfigurer.java, modules/swagger-core/src/test/java/io/swagger/matchers/SerializationMatchers.java, modules/swagger-jaxrs/src/test/java/io/swagger/ReferenceTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/models/ModelWithReferences.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithMoreReferences.java, modules/swagger-jaxrs/src/test/resources/ResourceWithMoreReferences.json, modules/swagger-jaxrs/src/test/resources/ResourceWithMoreReferencesAsOriginalRef.json, modules/swagger-jaxrs/src/test/resources/ResourceWithMoreReferencesWithInternalRef.json, modules/swagger-models/src/main/java/io/swagger/models/RefModel.java, modules/swagger-models/src/main/java/io/swagger/models/RefPath.java, modules/swagger-models/src/main/java/io/swagger/models/RefResponse.java, modules/swagger-models/src/main/java/io/swagger/models/parameters/RefParameter.java, modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java, modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java, modules/swagger-models/src/main/java/io/swagger/models/refs/GenericRef.java, modules/swagger-models/src/main/java/io/swagger/models/utils/PropertyModelConverter.java
This PR addresses issues related to "reference items" instantiation, serialization and resolving, triggered originally by swagger-api/swagger-parser/issues/727 and swagger-api/swagger-parser/issues/713; it would replace #2847
It updates related code mainly:
- providing an `originalRef` getter in "reference items" (e.g. `RefModel`, `RefProperty`, etc)
- allowing to have this `originalRef` mapped to `$ref` JSON property via MixIn or added `ReferenceSerializationConfigurer` helper class
- updating the ref parsing logic to identify as relative ref (and therefore not treating it as internal, which modifies the reference by adding the related prefix) non absolute nor explicitly internal properties containing a dot
- allowing to maintain  previous parsing behaviour by invoking at bootstrap …
=> refactor and fix references handling

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
So it can be overridden in subclasses (eg a scala model resolver)
=> Make ModelResolver _isOptionalType protected

modules/swagger-gradle-plugin/README.md, modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java, modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/GenericOpenApiContext.java, modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/SwaggerConfiguration.java, modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/ObjectMapperProcessor.java, modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/OpenAPIConfiguration.java, modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/OpenApiContext.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/ServletConfigContextUtils.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/ServletOpenApiConfigurationLoader.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/SwaggerLoader.java, modules/swagger-maven-plugin/README.md, modules/swagger-maven-plugin/src/main/java/io/swagger/v3/plugin/maven/SwaggerMojo.java
refs #2971 - adds modelConverterClasses and objectMapperProcessorClass to config
=> refs #2971 - adds modelConverterClasses and objectMapperProcessorClass to config

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java
The annotation @ApplicationPath is now scanned on the superclasses in order to work as intended with Weld proxies.
=> Fix for Issue #2966

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/XMLInfoTest.java
…solver.ignore() to get a more accurate approximation of what Jackson does
=> fix for issue #2907 - 1.5.x version

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket2972Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/resources/TestObject2972.java
Thanks a lot to @wcicola for spotting and working on this!
this replaces #2997 applying existing mechanism to Map schemas
=> ref #2972 - fixes resolving multiple map properties

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java
Issue #3082 
I check the Reader class in the jaxrs module. The parameter types are taken from the AnnotatedMethod object. For the return type, the type from the java method is used. 
I create simple fix and a pull request.
Could you please look at it if it is ok or create another solution for this issue.
Thanks
Andrej
=> #3082 jaxrs generic return type is abstract class

modules/swagger-models/src/main/java/io/swagger/models/properties/ObjectProperty.java, modules/swagger-models/src/test/java/io/swagger/models/properties/ObjectPropertyTest.java
Addresses https://github.com/swagger-api/swagger-core/issues/3084
=> Consider properties for equality of ObjectProperty

.gitignore, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/ArraySchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/BinarySchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/BooleanSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/ByteArraySchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/ComposedSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/DateSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/DateTimeSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/EmailSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/FileSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/IntegerSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/MapSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/NumberSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/ObjectSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/PasswordSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/StringSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/UUIDSchema.java
Why:
The various Schema subclasses (ArraySchema, BinarySchema, etc.) are
defined such that they actually duplicate some of the fields from
the Schema super class (e.g. type, format, default, etc.).  This
can create confusion when examining instances of these classes within
a debugger as you will see two "type" fields for example, the base class'
"type" field will be set to null and the subclass' "type" field will be set
to "array" (or "binary", or "boolean", etc.).   We have similar issues with
the format and default fields.
What:
In this PR, I've fixed this by adding a protected ctor to Schema, and default ctors to
the subclasses, plus I've removed some getters/setters from the subclasses
that are no longer needed.
=> fix #3094 - avoid duplicate fields in schema classes

modules/swagger-core/src/main/java/io/swagger/v3/core/util/PrimitiveType.java
`@Schema(`type` = "boolean") test_boolean:MyBooleanClass = false`
Specifying type=boolean in the schema always produces type:Object in the resulting json. I have tracked the issue down to PrimitiveType.java in package io.swagger.v3.core.util
It appears that
`dms.put("boolean", "boolean");`
Should be :
`dms.put("boolean_", "boolean");`
=> fix #3088 - fixes boolean @type annotation

modules/swagger-gradle-plugin/README.md
- Fix: show correct GAV coordinates for swagger-gradle-plugin when using the Gradle buildscript Syntax
=> Ticket-3115: Documentation for the swagger-gradle-plugin appears to give incorrect artifact path

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java
Making the main Reader.parseMethod protected greatly improves extensibility.
The method being private requires me to override the 3 corresponding public methods. Additionally, I need a callback reference (`java.util.function.Function`) for each of them just to simulate a `super` call in the one “overriding“ method.
=> Make parseMethod protected thus improving extensibility.

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java
A composed schema usually has sub schemas. So there is no need to set the default type "string" unless explicitly set. Setting it may lead to an unexpected semantic of the composed schema.
=> Do not set default type string for composed schema.

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java
When merging form parameters to one schema for the response body, the information about whether a parameter is taken over to the merged schema.
=> Respect required status of form parameters.

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/ComposedSchemaTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/InheritedBeanTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3030Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3063Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3197Test.java, modules/swagger-core/src/test/resources/AbstractBaseModelWithoutFields.json, modules/swagger-core/src/test/resources/Animal.json, modules/swagger-core/src/test/resources/AnimalClass.json, modules/swagger-core/src/test/resources/AnimalWithSchemaSubtypes.json, modules/swagger-core/src/test/resources/ModelWithFieldWithSubTypes.json, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java
includes and replaces #3228. Also fixes #3030, #3063 and #2989.
available in upcoming  version `2.0.9`, default behaviour for scenarios as in tickets #3030, #3063, #3197 change: 
properties of schemas resolved as `ComposedSchema` with non empty `allOf` are resolved as part of an object schema within the `allOf`.
This is semantically equivalent to the previous behaviour but better supported by other tools.
Previous behaviour can be maintained by providing a system property `composed-model-properties-as-sibiling` or by setting `ModelResolver.composedModelPropertiesAsSibling = true` programmatically
=>  refs #3197 - resolve properties within allOf for composed schemas

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java
as is not required and returns Void by default.
=> correcting JsonSerialize as check

modules/swagger-core/pom.xml, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/mixin/DateTimeSchemaMixin.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ObjectMapperFactory.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Ticket2340Resource.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/DateTimeSchema.java, pom.xml
"minor" breaking change, in cases of client projects using swagger-models or swagger-core , and relying on the java generic type of DateTimeSchema being Date, as the fix changes that to correctly use java 8 OffsetDateTime instead.
=> fix DateTimeSchema example serialization by updating type to OffsetDateTime

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/JaxrsAnnotationScanner.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/JaxrsApplicationAndResourcePackagesAnnotationScanner.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/integration/IntegrationTest.java
As mentioned in #3283, since version `2.0.7` default resource scanning behaviour has changed in scenarios where no resource packages or classes are defined; in versions up to `2.0.6` no resources would have been added except the ones defined in custom `Application.classes()`; since `2.0.7` the whole classpath is instead scanned. 
This PR adds a [scanner implementation](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-configuration#resource-scanning)  `JaxrsApplicationAndResourcePackagesAnnotationScanner` which behaves as pre `2.0.7` default mechanism
=> refs #3283 - add scanner limited to defined resourcePackages

modules/swagger-core/src/main/java/io/swagger/jackson/AbstractModelConverter.java, modules/swagger-jaxrs/src/test/java/io/swagger/SimpleReaderTest.java, modules/swagger-jaxrs/src/test/java/io/swagger/resources/Issue3286Resource.java
up to `1.5.23` release any defined `JsonRootName` annotation on a model takes precedence over a 
defined `ApiModel.value` annotation on the same model, causing e.g. issues like the one described in #3286. This PR addresses this by reversing the logic in such cases.
**Note** this breaks default behaviour in such scenarios comparing to previous versions, as an expected effect, given that previous logic can be considered a bug, as swagger annotations must take precedence to provide full control of the resolved spec.
To maintain previous behavior for any reason, a custom model resolver can be provided:
```
class CustomSchemaNameResolverConverter extends ModelResolver {
public CustomSchemaNameResolverConverter(ObjectMapper mapper) {
super(mapper);
}
protected boolean …
```
=> fix #3286 - prioritize schema name resolving by `ApiModel.value`

modules/swagger-models/src/main/java/io/swagger/models/Contact.java
This issue was reported on https://github.com/swagger-api/swagger-parser/issues/1204.
and reading the spec for 2.0 swagger version, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#contact-object has the vendor extension as valid.
That's the reason for the PR, to add vendor extension for contact object in core, and fix the issue in parser to be able to deserialize it validly.
pre-requisite for Parser issue #1204
=> Contact Model has no Vendor Extensions

modules/swagger-gradle-plugin/README.md, modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java
includes and replaces #3123 
**NOTE**:  since version `2.0.10` Gradle versions < 3.2 are not anymore supported
=> Enable caching of Gradle 'ResolveTask' - remove compatibility to Gradle versions prior to 3.2

modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java
This pull request fix this issue: https://github.com/swagger-api/swagger-core/issues/3295
=>  Add possibility to NOT expand super types while using setScan 

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/ExampleObject.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/examples/ExamplesTest.java, modules/swagger-jaxrs2/src/test/resources/examples/ParameterExample.yaml
introduces `@ExampleObject.description` annotation member, and resolves it when present, instead of populating `description` with the value of `@ExampleObject.name`
=> refs #3341 - add description to @ExampleObject annotation

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/EnumPropertyTest.java
- Fixes if-statement in ModelResolver to not treat non-enum models as enums when enumsAsRef is globally enabled
- Adds a comment explaining the purpose of the enumsAsRef global property in ModelResolver
=> fix #3414 - fix enumsAsRef global property behavior

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/TypeNameResolver.java
This change will enable  fully qualified java class names to be
displayed in api-docs and swagger-ui.
By default original behaviour will continue.
When needed fqns can be enabled by invoking
TypeNameResolver.std.setUseFqn(true);
=> Enabling fully qualified java class names 

modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverters.java
Sometimes, it's useful to be able to list registered converters to know if we need to add some converter. For example, we needed that for the springdoc-openapi project to allow tests running in parallel (avoiding them to all add the same converters when different spring contexts are present).
=> feature: listing registered converters

modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java
The warning message was speaking of DefaultValue instead of Example.
The warning message was using defaultValue instead of example.
The Boolean conversion was using  defaultValue instead of example.
=> Fix copy-paste issues in AbstractSerializableParameter.getExample 

modules/swagger-core/pom.xml, modules/swagger-hibernate-validations/pom.xml
Currently, Swagger Core depends on `javax.validation` API v1.1, strict. The OSGi manifest correctly includes the `javax.validation` API range as part of `Import-Package` instructions set: `javax.validation.constraints;version="[1.1,2)"`
The `javax.validation` API v1.1 is superseded by v2.0 and is rarely used. The version range for OSGi deployments could be relaxed to include v2.0 as well: `javax.validation.constraints;version="[1.1,3)"`. 
```
<Import-Package>javax.validation.constraints;version="[1.1,3)",*</Import-Package>
```
This is the only change in `MANIFEST.MF` (pretty minor) but it would actually relax the `javax.validation` version requirements and allow to use Swagger Core with Bean Validation 2.0 and/or with Jakarta artifacts inside OSGi container.
@frantuma this is backport of …
=> Relax Swagger Core 1.6.x OSGi constraints to allow usage of the Bean Validation API 1.1/2.0

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/EnumPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/models/JacksonNumberValueEnum.java, modules/swagger-core/src/test/java/io/swagger/models/JacksonPropertyEnum.java, modules/swagger-core/src/test/java/io/swagger/models/JacksonValueEnum.java, modules/swagger-core/src/test/java/io/swagger/models/ModelWithJacksonEnumField.java
This PR adds the feature from #3553 to the 1.5 branch. It allows to override enum values with the Jackson-specific annotations @JsonProperty or @JsonValue.
Since the 1.5 branch uses source target setting for Java 7, the `stream` API and `Optional` are not available. The code from the master branch was adapted to work without these. Except from that, the changes from the #3553 PR have all been ported into this PR, including the corresponding tests.
Closes #3616
=> Backport from master to 1.5 for support to override enum values

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/tags/Tags.java
add a missing 'a' so that everything looks perfect now :)
=> Fix omitted char in javadoc

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/JsonPropertyTest.java
This partially addresses #2845 and #3442; please see [this comment in test](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/JsonPropertyTest.java#L147) about further work needed to add full support
=> refs #2845 - resolve  @JsonIgnoreProperties as property annotation (partial support)

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ParameterProcessor.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/UrlEncodedResourceWithEncodings.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Encoding.java
related to #3643, #3282 and [this question](https://community.smartbear.com/t5/Swagger-Open-Source-Tools/Specifying-Encoding-For-Form-Data-Parameters/m-p/206091#M1362)
replaces #3644, adds @Parameter support for `form` parameters, allowing to specify encoding and description, e.g.
```java
@Parameter(name = "id", style = ParameterStyle.FORM, explode = TRUE, description = "id param") @FormParam( "id" ) List<String> ids
```
see also related test
=> refs #3643, refs #3282, resolve @Parameter for form params

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SwaggerAnnotationIntrospector.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3697Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/resources/TestObject3697.java
This implements better support for `@Hidden` and `@Schema.hidden` resolving in POJOs properties, allowing to mark any accessor (field, getter, setter or constructor) with `@Hidden` not to include the property in the resulting spec. This differs from previous behaviour where all accessors needed to be marked, and as in #3697 in some cases this wasn't sufficient. 
Also fixes #3560
=> refs #3697 - fix @Hidden and @Schema.hidden resolving

modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/HiddenFieldTest.java
=> Add test for hidden field in JsonCreator

modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java
The use of a set to filter dublicated jars in the resolve task, resulted
in an unstable ordering of the urls. This caused the resolve task to
fail on some machines and not on other, caused by the url paths.
Fixes #3876
=> Fix unstable ordering of urls in gradle resolve task

modules/swagger-project-jakarta/modules/swagger-maven-plugin-jakarta/src/main/java/io/swagger/v3/plugin/maven/jakarta/JakartaTransformer.java
@frantuma Validating the SNAPSHOT builds for refs #3836 on my end
- Files.copy(...) failed with DirectoryNotEmptyException (see [docs](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#copy%28java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...%29))
- URI.create(...) failed due to backwards slashes in outJarPath
=> Fix build on Windows OS

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/JsonIdentityTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/ModelWithJsonIdentity.java
=> fix NPE with @JsonIdentityInfo at class level

modules/swagger-models/src/main/java/io/swagger/models/auth/AuthorizationValue.java, modules/swagger-models/src/main/java/io/swagger/models/auth/UrlMatcher.java
add url List to authorizationValue
prerequisite for: https://github.com/swagger-api/swagger-parser/pull/1594
=> add url List to authorizationValue

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/reflection/ReflectionUtilsTest.java
see the issue for details
Refs #4002
=> fix: check all parents for further parameter annotations

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/EnumTest.java
This is a fix for enums with unbounded wildcards. We get a NullPointerException otherwise because `enumConstants` is `null`.
=> fix: Support enums with unbounded wildcards

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/PojoTest.java
fixes #4041
changes the default value for schema to serialize to object if this is possible, otherwise returns string
Note: this issue title is asking about the swagger-maven-plugin. The issue is not in this module, it is in swagger-core.  The issue can be re-created using the swaggger-maven-plugin, but that is to say, the swagger-maven-plugin is just one specific way to invoke the model resolution in swagger-core where this issue happens.
=> Issue 4041 schema json object defaultValue

modules/swagger-project-jakarta/pom.xml, pom.xml
This resolves #4145, the jackson-databind CVE.
A similar patch is also made in swagger-parser (swagger-parser#1690)
=> CVE-2020-36518: Bump jackson-databind to 2.13.2.2

modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java
Fixed a problem where `Schema` was not using the `items` property in the `equals()` or `hashcode()` method. This appears to have been missed when moving the `items` property off of the `ArraySchema` class and onto the `Schema` class.
=> Added items to Schema equals and hashcode

modules/swagger-core/src/main/java/io/swagger/v3/core/util/SecuritySchemeDeserializer.java, modules/swagger-core/src/test/java/io/swagger/v3/core/serialization/SecurityDefinitionTest.java, modules/swagger-core/src/test/resources/specFiles/securitySchemaWithExtension.json
Motivation
According to the specification the "Security Scheme Object" may be extended with Specification Extensions.
Modification
* Add test to highlight the bug
* SecuritySchemeDeserializer now parse other field
=> Json deserialization process should not remove extension for Security Scheme

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket3699Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/resources/TestObject3699.java
Custom name from @JsonTypeName should be used for wrapped JSON with @JsonTypeInfo(use = NAME, include = WRAPPER_OBJECT) (if class is annotated with @JsonTypeName )
See #3699
=> Add @JsonTypeName support for wrapped JSON

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-project-jakarta/pom.xml, pom.xml
refs https://github.com/swagger-api/swagger-core/issues/4212 - update jackson API usage to support Jackson < 2.9
=> refs #4212 - update jackson API usage to support Jackson < 2.9

modules/swagger-core/src/test/java/io/swagger/v3/core/serialization/OpenAPI3_1SerializationTest.java
`Json31.pretty(String)` uses Jackson's `DefaultIndenter` which uses the machine's line separator (`System.getProperty("line.separator")`), i.e. `"\r\n"` under Windows OS.
Fixes #4280
=> Fix #4280: Building swagger-core fails on Windows

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/ModelPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/RequiredFields.java
=> feat: replace required attribute on @Schema by requiredMode

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/EnumPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonNumberValueEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonNumberValueFieldEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonValueFieldEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonValuePrivateEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ModelWithJacksonEnumField.java
This fixes issue 3998. If there exist jackson fields, or private methods, then jackson will serialize these as the values for an enum. This enables looking for those values first before using the enum field name.
=> fix #3998 model schema enum values of jackson fields and private methods

modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/jackson/ModelResolverTest.java
In addition to the hard coded `Optional` reference types the type information from jackson is used to unwrap additional reference types (e.g. `AtomicReference`)
Fixes #4103 for 1.5 branch (swagger 1.6.X)
=> #4103 Support for Jackson reference types

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReferenceTypeUtils.java
New code in ReferenceTypeUtils causes exception when using swagger-core with Scala Options.
```
java.lang.IllegalArgumentException: argument "t" is null
at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4885)
at com.fasterxml.jackson.databind.ObjectMapper.constructType(ObjectMapper.java:2211)
at io.swagger.v3.core.util.ReferenceTypeUtils.unwrapReference(ReferenceTypeUtils.java:35)
at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:79)
at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:81)
at io.swagger.v3.core.converter.ModelConverters.readAll(ModelConverters.java:89)
at io.swagger.v3.core.converter.ModelConverters.readAll(ModelConverters.java:80)
at …
```
=> new ReferenceTypeUtils code fails with IllegalArgumentException with type.getType() is null

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReferenceTypeUtils.java
Relates to https://github.com/swagger-api/swagger-core/pull/4297
=> fix handling for case where type.getType() is null

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket4362Test.java
This PR does the following:
- Fixes `NullPointerException` thrown when `ModelResolver.enumsAsRef` is set to `true`  and schema is being resolved for enum located `java.` or `javax.` package (e.g. `java.time.DayOfWeek` or `java.time.Month`)
Fixes https://github.com/swagger-api/swagger-core/issues/4362
=> Fix for #4362 - Resolving Schema for system enums fails if enumsAsRef is enabled

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket4239Test.java
Forward JsonView annotation when resolving subtypes.
Fixes #4239
=> Fix #4239: @JsonView ignored for subclasses

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java
Hello,
CompletionStage is officially supported since JavaEE JaxRS2.1 (see official specs [here](https://github.com/javaee/jax-rs-spec/blob/2.1/spec.pdf), page 55: 8.2.2 CompletionStage), same goes for Jakarta restful-ws (see official specs [here](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html), 8.2.2 CompletionStage)
This PR adds an extraction of `CompletionStage` associated type.
=> Support of CompletionStage (JaxRS 2.1)

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
Rather than ignoring all properties with @JsonIgnoreProperties, we only ignore if it doesn't have the "allowGetters" = true
Since if it allowsGetters, you are going to receive it as part of the response
https://github.com/swagger-api/swagger-core/issues/3410
https://github.com/swagger-api/swagger-core/issues/4416
For example, the following line would cause var1 and var2 to be excluded:
`@JsonIgnoreProperties(value = { "var1" , "var2" })`
However if it has allowGetters, it isn't excluded
`@JsonIgnoreProperties(value = { "var1" , "var2" }, allowGetters = true`
=> Change ModelResolver to better handle JsonIgnoreProperties

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonNumberValueEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonNumberValueFieldEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonPropertyEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonValueEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonValueFieldEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonValuePrivateEnum.java
This fixes #3581
If you place Hidden annotation on enum constant this value will be excluded from swagger model.
=> fix #3581: recognize Hidden annotation on enum values.

modules/swagger-core/src/main/java/io/swagger/v3/core/util/ReflectionUtils.java
refs #4589 relatively to the `error` log
=> Replace log error with warning in reflection with type not found

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/headers/Header.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/AnnotationsUtilsHeadersTest.java, modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/OperationParser.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/annotations/operations/AnnotatedOperationMethodTest.java
=> Add Header Object missing attributes

modules/swagger-core/src/main/java/io/swagger/v3/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/v3/core/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/3.1.0/list-3.1.json
=> Fix #4618: process array schema in OpenAPI 3.1 same as in OpenAPI 3.0

modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/ext/OpenAPIExtensions.java
Fixes #3726.
I tested this locally on my own project. When the appropriate file exists in META-INF/services, the OpenAPIExtension is loaded properly by the Gradle plugin after this change.
=> fix: Add class loader to OpenAPIExtensions ServiceLoader

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/PrimitiveType.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/BinaryParameterResourceTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/BinaryParameterResource.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/model/Item.java, modules/swagger-jaxrs2/src/test/resources/BinaryParameterResource.yaml, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/BinarySchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/ByteArraySchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java
Includes and replaces https://github.com/swagger-api/swagger-core/pull/3955
Closes https://github.com/swagger-api/swagger-core/issues/3944 and https://github.com/swagger-api/swagger-core/issues/3511.
See also https://github.com/swagger-api/swagger-parser/issues/1630
It introduces [binary-string-conversion](https://github.com/swagger-api/swagger-core/pull/4659/files#diff-cb2ef0df3091032171d05fded8d3f06c1679574101437806921706be09cad764R30) env or system variable, allowing to define behavior for resolution and conversion of byte arrays:
binary-string-conversion = base64 : resolves into ByteArraySchema/BinarySchema using Base64 for casting/conversion
binary-string-conversion = string-schema : resolves into StringSchema
=> Support proper mapping of the byte array

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java
By creating an ArraySchema rather than JsonSchema, the type is correctly set to "array".
=> Missing array type when using @ArraySchema

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/ModelResolverOAS31Test.java
Refs:
- https://github.com/swagger-api/swagger-core/issues/4702
- https://github.com/swagger-api/swagger-core/issues/4703
=> refs-#4703/#4702-@Pattern/@Size annotations handling on collections

modules/swagger-core/src/main/java/io/swagger/v3/core/util/Json.java
Closes #4672 
Instead of following the suggested approach in the issue, a more elegant method was used, where the initialization is delegated to the JVM code for static initialization.
See https://stackoverflow.com/questions/8297705/how-to-implement-thread-safe-lazy-initialization for a thread about this implementation.
See also https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom for the chosen pattern.
=> Fix thread safety in `Json.mapper()`

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/serialization/OpenAPI3_1SerializationTest.java
Fixes #4657
Extra: fixed yaml checks - yaml by default always uses \n separator
=> Removed unnecessary cast that crashes for 3.1 schema

modules/swagger-core/src/main/java/io/swagger/v3/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/v3/core/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/3.1.0/issue-4737-3.1.yaml, modules/swagger-core/src/test/resources/specFiles/3.1.0/specWithReferredSchemas-3.1.yaml
=> refs-#4737 add scanning for other OAS elements besides paths

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-java17-support/src/test/java/io/swagger/v3/java17/resolving/JavaRecordTest.java
This PR fixes problem with ignored validation annotations when used on generic type arguments in Java Records components.
=> Fix java record type use annotations support

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
The latest Swagger Core `2.2.26` raises `java.lang.NullPointerException` and prints the stack trace into the console while attempting to introspect if the type is a record or not:
```
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.introspect.AnnotatedMember.getDeclaringClass()" because the return value of "com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition.getPrimaryMember()" is null
at io.swagger.v3.core.jackson.ModelResolver.isRecordType(ModelResolver.java:1131)
at io.swagger.v3.core.jackson.ModelResolver.extractGenericTypeArgumentAnnotations(ModelResolver.java:1109)
at io.swagger.v3.core.jackson.ModelResolver.addGenericTypeArgumentAnnotationsForOptionalField(ModelResolver.java:1104)
at …
```
=> Fix java.lang.NullPointerException and remove stack trace output from ModelResolver

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
Simply moves the applySchemaResolution check to a method on ModelResolver.
This way we can configure behavior in a custom ModelResolver subclass by overriding the method.
=> Move applySchemaResolution check to a method

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-java17-support/src/test/java/io/swagger/v3/java17/resolving/JavaRecordTest.java
Add support for record classes with `@JsonProperty` annotations that do not match the field names when getting the component annotations. 
When these two differ a NoSuchMethodException is throw. Instead access the declared method using the name of the primary member.
=> Fix for record component annotations on fields with JsonProperty annotations

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/AbstractModelConverter.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
Do not cache the value of '_intr' because users can load custom modules later after swagger is configured, and we want to utilize their annotation inspection, just like jackson would do.
=> Fix: Avoid caching AnnotationIntrospector to support custom module loading

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java
Issue ticket:
https://github.com/swagger-api/swagger-core/issues/4781
=> [BUGFIX] Jackson/@JsonUnwrapped - unwrapping fails when innerModel.$ref not null

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/TypeNameResolver.java
Fixes swagger semantic errors:
1. Component names can only contain the characters A-Z a-z 0-9 - . _
2. $ref values must be RFC3986-compliant percent-encoded URIs
=> fix: Replace $ in the FQN of the class

modules/swagger-core/src/main/java/io/swagger/v3/core/filter/SpecFilter.java, modules/swagger-core/src/test/java/io/swagger/v3/core/filter/SpecFilterTest.java, modules/swagger-core/src/test/resources/specFiles/3.1.0/composed-schema-3.1.json
- add support for patternProperties in SpecFilter
- fix #4817
=> fix patternproperties handling in SpecFilter

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ModelDeserializer.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/ParameterProcessor.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/PrimitiveType.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/ModelResolverOAS31Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/Address.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/PostalCodeNumberPattern.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/PostalCodePattern.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/Ticket4879Resource.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/ArbitrarySchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/JsonSchema.java, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java
This PR addresses the following tickets:
* #4798
* #4625
* #4457
* #4014
* #3834
* #4792 
Changes include:
* use correct `Schema` hierarchy for 3.0 and 3.1 
* update casting for 3.1
* update `object` type resolution 
* introducing `explicit-object-schema` and `use-arbitrary-schema` sys/env props
These 2 properties allow to tweak the processing of  Schema `type`. By default
* for OAS 3.0 a `type: object` is added whenever any class (even `java.lang.Object`) is resolved into a schema and no type is defined in annotations or elsewhere. This behavior is unchanged (see below to customize) for compatibility reasons
* for OAS 3.1 `type: object` is NOT added when type is not defined and there are not Object Schema-specific properties resolved for that schema.
this behavior can be customized by …
=> update Schema resolution and casting - add `explicit-object-schema` and `use-arbitrary-schema` sys/env props

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/BeanValidationsModel.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/BeanValidatorTest.java
Fields annotated with `@Email` are now mapped to `EmailSchema`.
=> Add support for jakarta.validation.constraints.Email

modules/swagger-core/pom.xml, modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/OpenAPI3_1DeserializationTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/properties/MapPropertyDeserializerTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/AnnotationsUtilsExtensionsTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/AnnotationsUtilsHeadersTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/BeanValidatorTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/ComposedSchemaTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/JsonViewTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/Ticket2884Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/serialization/SecurityDefinitionTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/AnnotationsUtilsTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/ReferenceTypeUtilsTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/util/reflection/ReflectionUtilsTest.java, modules/swagger-eclipse-transformer-maven-plugin/pom.xml, modules/swagger-gradle-plugin/build.gradle, modules/swagger-gradle-plugin/src/test/java/io/swagger/v3/plugins/gradle/SwaggerResolveTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/BeanParamTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/DecoratorExtensionTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/FormParamBeanTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/JsonViewTest.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/it/OpenApiResourceIT.java, modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/util/ServletUtilsTest.java, modules/swagger-models/src/test/java/io/swagger/test/SchemaTests.java, modules/swagger-models/src/test/java/io/swagger/v3/oas/models/PathsTest.java, modules/swagger-models/src/test/java/io/swagger/v3/oas/models/links/LinkParameterTest.java, modules/swagger-project-jakarta/pom.xml, pom.xml
Includes and replaces #4879 (fixes gradle test), @strangelookingnerd thanks! 
This PR aims to _remove_ usage of JUnit and consistently use TestNG across the modules instead.
Changes include:
* Use TestNG annotations over JUnit counterparts
* Use TestNG assertions over JUnit counterparts (also simplify some assertions in the process)
* Consistently use static imports for TestNG assertions
* Remove JUnit depencency if not required
* Add TestNG dependency if required
There is one exception in `swagger-maven-plugin` where JUnit is still required by the underlying maven test suite and thus tests can not be migrated.
=> Consistent usage of TestNG

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/BeanValidationsModel.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/BeanValidatorTest.java
https://jakarta.ee/specifications/annotations/3.0/apidocs/jakarta.annotation/jakarta/annotation/nonnull
Items annotated with `Nonnull` should be treated as required items.
=> Include Nonnull annotation from Jakarta Annotations for required items

modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/Ticket3900Test.java
Potentially resolves
- #3900
- #4753
- #3561
=> Add unittest for v3.1 which has both ref and description

modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/EnumPropertyTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonIntegerValueEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonIntegerValueFieldEnum.java, modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/ModelWithJacksonEnumField.java
Refactor the method for generating enum schemas to better handle type-specific schemas, such as IntegerSchema. This change ensures that integer-based enums are correctly represented in the generated schemas.
fixes https://github.com/swagger-api/swagger-core/issues/4768
=> feat: Support other types than string in enum schemas

modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/converting/SwaggerSerializerTest.java, modules/swagger-core/src/test/java/io/swagger/v3/core/deserialization/OpenAPI3_1DeserializationTest.java, modules/swagger-core/src/test/resources/specFiles/3.1.0/specWithDynamicRef.yaml, modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java
=> Add $dynamicRef

.github/workflows/maven-pulls.yml, .github/workflows/maven.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml, CI/CI.md, modules/swagger-project-jakarta/pom.xml, pom.xml
see https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
To be merged after OSSRH repo has been manually moved by Sonatype Support to Central Portal
=> chore: migrate Sonatype OSSRH to Central Portal

.github/workflows/maven-v1-pulls.yml, .github/workflows/maven-v1.yml, README.md, pom.xml
[fix: fix README](https://github.com/swagger-api/swagger-core/commit/244adc2c626a67283ef3c4dd44a404741e7f3aa6)
[update dependencies](https://github.com/swagger-api/swagger-core/commit/60ad4cc4da651d8153471135c1a5ee399c3bc8aa)
[chore: migrate Sonatype OSSRH to Central Portal](https://github.com/swagger-api/swagger-core/commit/bcfbbb00f204a93928007764bab625e42663a003)
=> migrate Sonatype OSSRH to Central Portal

modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/ModelResolverOAS31Test.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/CreditCard.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/Currency.java
=> fix: Fix missing items on nested @ArraySchema items in OAS 3.1

modules/swagger-core/src/main/java/io/swagger/v3/core/converter/AnnotatedType.java, modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java, modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java, modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/EnumTest.java
fix: reattach enumAsRef for OAS 3.1 and OAS 3.0 with ALL_OF. Fixes #4932
=> refs enumAsRef Issue 4932
